{
 "title": "Workers",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "provisioner",
    "query": "SHOW TAG VALUES FROM tc_queue_exec WITH KEY = \"provisionerId\""
   },
   {
    "name": "workerType",
    "query": "SHOW TAG VALUES FROM tc_queue_exec WITH KEY = \"workerType\" WHERE provisionerId =~ /$provisioner/"
   },
   { "name": "filter" },
   { "name": "alert_filter", "label": "alert filter" }
  ]
 },
 "panels": [
  {
   "title": "Task Errors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval * 20" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "task error" },
      { "condition": "AND", "key": "host", "operator": "!~", "value": "/^DESKTOP/" }
     ]
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pending $tag_workerType",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "started",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/^task start/" },
      { "condition": "AND", "key": "host", "operator": "!~", "value": "/^DESKTOP/" }
     ]
    },
    {
     "alias": "task error",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/^task error/" },
      { "condition": "AND", "key": "host", "operator": "!~", "value": "/^DESKTOP/" }
     ]
    }
   ]
  },
  {
   "title": "AWS Workers Provisioned",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "aws-provisionerhttp",
     "select": [
      [
       { "params": [ "runningCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HW Dead Workers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 14 },
   "repeat": "platform",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_level",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "alerts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "alertName", "operator": "=", "value": "RelOps deadman workers" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla/" }
     ]
    }
   ]
  },
  {
   "title": "Hardware Dead Worker Alerts",
   "type": "table",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "alerts",
     "query": "SELECT last(\"duration\") /(1000*1000*1000*60) AS \"duration\", last(\"message\"), last(\"value\") AS \"log messages\" FROM \"autogen\".\"alerts\" WHERE (\"alertName\" = 'RelOps deadman workers') AND \"host\" =~ /mdc[0-9].mozilla/ AND $timeFilter AND \"host\" !~ /^DESKTOP/ GROUP BY \"host\" ORDER BY time DESC",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "duration" ], "type": "alias" }
      ],
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "message" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "log messages" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "alertName", "operator": "=", "value": "RelOps deadman workers" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$platform/" }
     ]
    }
   ]
  },
  {
   "title": "Reimaged",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 20 },
   "targets": [
    {
     "alias": "$tag__host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "event" ], "type": "tag" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "deploystudio workflow" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "event" ], "type": "tag" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "new host puppet run" }
     ]
    }
   ]
  },
  {
   "title": "Tree status",
   "type": "table",
   "gridPos": { "h": 15, "w": 17, "x": 0, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo" ], "type": "tag" },
      { "params": [ "reason" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "who" ], "type": "tag" }
     ],
     "measurement": "treestatus_stack_exec",
     "query": "SELECT \"status_value\" FROM \"autogen\".\"treestatus_stack_exec\" WHERE (\"repo\" =~ /mozilla-[ribc]|^try$|^autoland$/ AND \"status\" = 'closed') AND $timeFilter GROUP BY \"repo\", \"reason\", \"status\", \"who\"",
     "select": [
      [
       { "params": [ "status_value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "repo",
       "operator": "=~",
       "value": "/mozilla-[ribc]|^try$|^autoland$/"
      },
      { "condition": "AND", "key": "status", "operator": "=", "value": "closed" }
     ]
    }
   ]
  }
 ]
}