{
 "title": "Android Queues - Breakdown",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Android Hardware (Bitbar) - GW ONLY",
   "type": "graph",
   "description": "proj-autophone/gecko-t-ap-*",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "jobs" }
   ],
   "targets": [
    {
     "alias": "$tag_queue",
     "groupBy": [
      { "params": [ "queue" ], "type": "tag" }
     ],
     "measurement": "current",
     "query": "SELECT * FROM \"bitbar_queue_size\" WHERE $timeFilter and queue =~ /gw/ GROUP BY \"queue\";\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "queue", "operator": "=", "value": "gecko-t-ap-batt-g5" }
     ]
    }
   ]
  },
  {
   "title": "current g-w jobs",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"bitbar_queue_size\" WHERE $timeFilter AND queue =~ /gw/ GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Android Hardware (Bitbar) - TC-W ONLY",
   "type": "graph",
   "description": "proj-autophone/gecko-t-ap-*",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "jobs" }
   ],
   "targets": [
    {
     "alias": "$tag_queue",
     "groupBy": [
      { "params": [ "queue" ], "type": "tag" }
     ],
     "measurement": "current",
     "query": "SELECT * FROM \"bitbar_queue_size\" WHERE $timeFilter and queue !~ /gw/ GROUP BY \"queue\";\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "queue", "operator": "=", "value": "gecko-t-ap-batt-g5" }
     ]
    }
   ]
  },
  {
   "title": "current tc-w jobs",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"bitbar_queue_size\" WHERE $timeFilter AND queue !~ /gw/ GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Android Emulated (AWS & Packet.net)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "jobs" }
   ],
   "targets": [
    {
     "alias": "$tag_provisionerId/$tag_workerType",
     "groupBy": [
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT * FROM \"bitbar_queue_size\" WHERE $timeFilter AND queue =~ /^$queue$/  GROUP BY \"queue\";\n",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "aws-provisioner-v1" },
      { "condition": "AND", "key": "workerType", "operator": "=", "value": "gecko-t-linux-xlarge" }
     ]
    },
    {
     "alias": "packet/$tag_workerType",
     "groupBy": [
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT * FROM \"bitbar_queue_size\" WHERE $timeFilter AND queue =~ /^$queue$/  GROUP BY \"queue\";\n",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "terraform-packet" },
      { "condition": "AND", "key": "workerType", "operator": "=", "value": "gecko-t-linux" }
     ]
    }
   ]
  }
 ]
}