{
 "title": "Android Queues",
 "tags": [
  "android",
  "hardware"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "queue",
    "label": "Bitbar Queue",
    "query": "SHOW TAG VALUES WITH KEY = \"queue\""
   }
  ]
 },
 "panels": [
  {
   "title": "Android Hardware (Bitbar)",
   "type": "graph",
   "description": "proj-autophone/gecko-t-ap-*",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "jobs" }
   ],
   "targets": [
    {
     "alias": "proj-autophone/$tag_queue",
     "groupBy": [
      { "params": [ "queue" ], "type": "tag" }
     ],
     "measurement": "current",
     "query": "SELECT * FROM \"bitbar_queue_size\" WHERE $timeFilter AND queue =~ /^$queue$/  GROUP BY \"queue\";\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "queue", "operator": "=", "value": "gecko-t-ap-batt-g5" }
     ]
    }
   ]
  },
  {
   "title": "Current Android HW Jobs",
   "type": "singlestat",
   "description": "all queues",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bitbar_queue_size",
     "query": "SELECT sum(\"value\") FROM \"bitbar_queue_size\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 3, "w": 5, "x": 19, "y": 8 } },
  {
   "title": "Android Emulated (AWS and Packet)",
   "type": "graph",
   "description": "aws queue shows non-android work",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "jobs" }
   ],
   "targets": [
    {
     "alias": "$tag_provisionerId/$tag_workerType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"pendingTasks\" FROM \"tc_queue_exec\" WHERE (\"provisionerId\" = 'aws-provisioner-v1' AND \"workerType\" = 'gecko-t-linux-xlarge') AND $timeFilter GROUP BY \"workerType\", \"provisionerId\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_provisionerId/$tag_workerType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"pendingTasks\" FROM \"tc_queue_exec\" WHERE (\"provisionerId\" = 'terraform-packet' AND \"workerType\" = 'gecko-t-linux') AND $timeFilter GROUP BY \"workerType\", \"provisionerId\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "see also",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 11 },
   "content": "[breakdown of tc-w and g-w jobs](https://grafana.relops.mozops.net/d/lDwNZA6ik/android-queues-breakdown?orgId=1&refresh=5m)\n\n\n\n"
  }
 ]
}