{
 "title": "Hardware Workers",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "workerType",
    "query": "SHOW TAG VALUES FROM \"autogen\".\"tc_queue2_exec\" WITH key = \"workerType\" WHERE \"provisionerId\" = 'releng-hardware'"
   }
  ]
 },
 "panels": [
  {
   "title": "Queued Tasks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"pendingTasks\") FROM \"autogen\".\"tc_queue2_exec\" WHERE (\"provisionerId\" = 'releng-hardware') AND $timeFilter GROUP BY time($__interval), \"workerType\" fill(previous)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "releng-hardware" }
     ]
    }
   ]
  },
  {
   "title": "Puppet config version",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT distinct(\"version_configstring\") FROM \"puppetagent\" WHERE $timeFilter GROUP BY workerType",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "releng-hardware" }
     ]
    }
   ]
  },
  {
   "title": "Generic Worker process reporting",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "worker proc $tag_workerType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT count(distinct(host)) FROM (SELECT \"cpu_usage\",\"host\" FROM \"autogen\".\"procstat\" WHERE $timeFilter) WHERE $timeFilter GROUP BY workerType, time($__interval * 10) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "t-linux64-ms-001" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT max(\"cpu_usage\") FROM \"autogen\".\"procstat\" WHERE $timeFilter GROUP BY workerType, time($__interval*20)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "t-linux64-ms-001" }
     ]
    }
   ]
  },
  {
   "title": "$workerType",
   "type": "graph",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 14 },
   "repeat": "workerType",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT count(distinct(host)) FROM (SELECT \"cpu_usage\",\"host\" FROM \"autogen\".\"procstat\" WHERE $timeFilter) WHERE $timeFilter  AND (\"workerType\" =~ /^$workerType$/) GROUP BY workerType, time($__interval * 10) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "t-linux64-ms-001" }
     ]
    },
    {
     "alias": "puppet failure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "puppetagent",
     "query": "SELECT sum(\"events_failure\") FROM \"puppetagent\" WHERE $timeFilter AND (\"workerType\" =~ /^$workerType$/) GROUP BY time($__interval), \"workerType\" fill(null)",
     "select": [
      [
       { "params": [ "events_failure" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT max(\"cpu_usage\") FROM \"autogen\".\"procstat\" WHERE $timeFilter  AND (\"workerType\" =~ /^$workerType$/) GROUP BY workerType, time($__interval*20)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "t-linux64-ms-001" }
     ]
    },
    {
     "alias": "queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pendingTasks\") FROM \"autogen\".\"tc_queue2_exec\" WHERE (\"provisionerId\" = 'releng-hardware') AND (\"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval), \"workerType\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$workerType",
   "type": "graph",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT count(distinct(host)) FROM (SELECT \"cpu_usage\",\"host\" FROM \"autogen\".\"procstat\" WHERE $timeFilter) WHERE $timeFilter  AND (\"workerType\" =~ /^$workerType$/) GROUP BY workerType, time($__interval * 10) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "t-linux64-ms-001" }
     ]
    },
    {
     "alias": "puppet failure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "puppetagent",
     "query": "SELECT sum(\"events_failure\") FROM \"puppetagent\" WHERE $timeFilter AND (\"workerType\" =~ /^$workerType$/) GROUP BY time($__interval), \"workerType\" fill(null)",
     "select": [
      [
       { "params": [ "events_failure" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT max(\"cpu_usage\") FROM \"autogen\".\"procstat\" WHERE $timeFilter  AND (\"workerType\" =~ /^$workerType$/) GROUP BY workerType, time($__interval*20)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "t-linux64-ms-001" }
     ]
    },
    {
     "alias": "queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pendingTasks\") FROM \"autogen\".\"tc_queue2_exec\" WHERE (\"provisionerId\" = 'releng-hardware') AND (\"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval), \"workerType\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$workerType",
   "type": "graph",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT count(distinct(host)) FROM (SELECT \"cpu_usage\",\"host\" FROM \"autogen\".\"procstat\" WHERE $timeFilter) WHERE $timeFilter  AND (\"workerType\" =~ /^$workerType$/) GROUP BY workerType, time($__interval * 10) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "t-linux64-ms-001" }
     ]
    },
    {
     "alias": "puppet failure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "puppetagent",
     "query": "SELECT sum(\"events_failure\") FROM \"puppetagent\" WHERE $timeFilter AND (\"workerType\" =~ /^$workerType$/) GROUP BY time($__interval), \"workerType\" fill(null)",
     "select": [
      [
       { "params": [ "events_failure" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT max(\"cpu_usage\") FROM \"autogen\".\"procstat\" WHERE $timeFilter  AND (\"workerType\" =~ /^$workerType$/) GROUP BY workerType, time($__interval*20)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "t-linux64-ms-001" }
     ]
    },
    {
     "alias": "queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pendingTasks\") FROM \"autogen\".\"tc_queue2_exec\" WHERE (\"provisionerId\" = 'releng-hardware') AND (\"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval), \"workerType\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$workerType",
   "type": "graph",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT count(distinct(host)) FROM (SELECT \"cpu_usage\",\"host\" FROM \"autogen\".\"procstat\" WHERE $timeFilter) WHERE $timeFilter  AND (\"workerType\" =~ /^$workerType$/) GROUP BY workerType, time($__interval * 10) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "t-linux64-ms-001" }
     ]
    },
    {
     "alias": "puppet failure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "puppetagent",
     "query": "SELECT sum(\"events_failure\") FROM \"puppetagent\" WHERE $timeFilter AND (\"workerType\" =~ /^$workerType$/) GROUP BY time($__interval), \"workerType\" fill(null)",
     "select": [
      [
       { "params": [ "events_failure" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT max(\"cpu_usage\") FROM \"autogen\".\"procstat\" WHERE $timeFilter  AND (\"workerType\" =~ /^$workerType$/) GROUP BY workerType, time($__interval*20)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "t-linux64-ms-001" }
     ]
    },
    {
     "alias": "queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pendingTasks\") FROM \"autogen\".\"tc_queue2_exec\" WHERE (\"provisionerId\" = 'releng-hardware') AND (\"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval), \"workerType\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$workerType",
   "type": "graph",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT count(distinct(host)) FROM (SELECT \"cpu_usage\",\"host\" FROM \"autogen\".\"procstat\" WHERE $timeFilter) WHERE $timeFilter  AND (\"workerType\" =~ /^$workerType$/) GROUP BY workerType, time($__interval * 10) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "t-linux64-ms-001" }
     ]
    },
    {
     "alias": "puppet failure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "puppetagent",
     "query": "SELECT sum(\"events_failure\") FROM \"puppetagent\" WHERE $timeFilter AND (\"workerType\" =~ /^$workerType$/) GROUP BY time($__interval), \"workerType\" fill(null)",
     "select": [
      [
       { "params": [ "events_failure" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT max(\"cpu_usage\") FROM \"autogen\".\"procstat\" WHERE $timeFilter  AND (\"workerType\" =~ /^$workerType$/) GROUP BY workerType, time($__interval*20)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "t-linux64-ms-001" }
     ]
    },
    {
     "alias": "queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pendingTasks\") FROM \"autogen\".\"tc_queue2_exec\" WHERE (\"provisionerId\" = 'releng-hardware') AND (\"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval), \"workerType\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$workerType",
   "type": "graph",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT count(distinct(host)) FROM (SELECT \"cpu_usage\",\"host\" FROM \"autogen\".\"procstat\" WHERE $timeFilter) WHERE $timeFilter  AND (\"workerType\" =~ /^$workerType$/) GROUP BY workerType, time($__interval * 10) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "t-linux64-ms-001" }
     ]
    },
    {
     "alias": "puppet failure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "puppetagent",
     "query": "SELECT sum(\"events_failure\") FROM \"puppetagent\" WHERE $timeFilter AND (\"workerType\" =~ /^$workerType$/) GROUP BY time($__interval), \"workerType\" fill(null)",
     "select": [
      [
       { "params": [ "events_failure" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT max(\"cpu_usage\") FROM \"autogen\".\"procstat\" WHERE $timeFilter  AND (\"workerType\" =~ /^$workerType$/) GROUP BY workerType, time($__interval*20)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "t-linux64-ms-001" }
     ]
    },
    {
     "alias": "queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pendingTasks\") FROM \"autogen\".\"tc_queue2_exec\" WHERE (\"provisionerId\" = 'releng-hardware') AND (\"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval), \"workerType\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}