{
 "title": "Android Queues",
 "tags": [
  "android_main_alerts",
  "android",
  "owner=relsre",
  "relsre-backup"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Android Hardware",
   "type": "timeseries",
   "description": "proj-autophone/gecko-t-ap-*",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by() (tc_queue2_prometheus_pending_tasks{provisioner=\"proj-autophone\"})",
     "legendFormat": "total tasks"
    },
    {
     "expr": "sum by(provisioner, workerType) ( tc_queue2_prometheus_pending_tasks{provisioner=\"proj-autophone\"})",
     "legendFormat": "{{provisioner}}/{{workerType}} tasks"
    },
    {
     "expr": "sum by(workerType) (tc_queue2_prometheus_running_workers{provisioner=\"proj-autophone\"}) / sum by(workerType) (tc_android_prometheus_worker_health_configured_devices{}) * 100",
     "legendFormat": "proj-autophone/{{workerType}} % workers in-use"
    }
   ]
  },
  {
   "title": "Android Hw Pending Tasks",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tc_queue2_prometheus_pending_tasks{provisioner=\"proj-autophone\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Android Hw - Bitbar Health",
   "type": "bargauge",
   "description": "uses Bitbar API (offline) and the bitbar-devicepool config",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "((sum(tc_android_prometheus_worker_health_configured_devices) - sum(tc_android_prometheus_worker_health_missing_or_offline_devices)) / sum(tc_android_prometheus_worker_health_configured_devices)) * 100"
    }
   ]
  },
  {
   "title": "Android Emulated",
   "type": "timeseries",
   "description": "aws queue shows non-android work",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(provisioner, workerType) (tc_queue2_prometheus_pending_tasks{provisioner=\"gecko-t\", workerType=~\".*kvm.*\"})",
     "legendFormat": "{{provisioner}}/{{workerType}} pending tasks"
    },
    {
     "expr": "sum by (provisioner, workerType) (tc_queue2_prometheus_running_workers{provisioner=\"gecko-t\", workerType=~\".*kvm.*\"})",
     "legendFormat": "{{provisioner}}/{{workerType}} running workers"
    }
   ]
  },
  {
   "title": "Android Em Pending Tasks",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tc_queue2_prometheus_pending_tasks{provisioner=\"gecko-t\", workerType=~\".*kvm.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RelSRE Alerts", "type": "alertlist", "gridPos": { "h": 25, "w": 9, "x": 0, "y": 20 } },
  {
   "title": "Android Hw Worker Details",
   "type": "table",
   "description": "configured from bitbar-devicepool, missing is from bd and tc, offline is from bitbar api",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 20 },
   "targets": [
    {
     "expr": "sum by (\"workerType\") (tc_android_prometheus_worker_health_configured_devices)",
     "legendFormat": "configured"
    },
    {
     "expr": "sum by(workerType) (tc_android_prometheus_worker_health_missing_or_offline_devices)",
     "legendFormat": "missing or offline"
    },
    {
     "expr": "sum by(workerType) (tc_queue2_prometheus_running_workers{provisioner=\"proj-autophone\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum by(workerType) (tc_queue2_prometheus_quarantined_workers{provisioner=\"proj-autophone\"})",
     "legendFormat": "quarantined"
    },
    {
     "expr": "sum by (workerType) (tc_android_prometheus_worker_health_missing_or_offline_devices)\n+ \nsum by (workerType) (tc_queue2_prometheus_quarantined_workers{provisioner=\"proj-autophone\"})\nor\nsum by (workerType) (tc_android_prometheus_worker_health_missing_or_offline_devices)\nor\nsum by (workerType) (tc_queue2_prometheus_quarantined_workers{provisioner=\"proj-autophone\"})\n",
     "legendFormat": "missing, offline, or quarantined"
    },
    {
     "expr": "(sum by (workerType) (tc_android_prometheus_worker_health_missing_or_offline_devices)\n+ \nsum by (workerType) (tc_queue2_prometheus_quarantined_workers{provisioner=\"proj-autophone\"})\nor\nsum by (workerType) (tc_android_prometheus_worker_health_missing_or_offline_devices)\nor\nsum by (workerType) (tc_queue2_prometheus_quarantined_workers{provisioner=\"proj-autophone\"})\n)\n/ (sum by (workerType) (tc_android_prometheus_worker_health_configured_devices))",
     "legendFormat": "problem percentage"
    }
   ]
  },
  {
   "title": "Android Em Worker Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 31 },
   "targets": [
    {
     "expr": "sum by(workerType, provisioner) (tc_queue2_prometheus_running_workers{provisioner=\"gecko-t\", workerType=~\".*kvm.*\"})",
     "legendFormat": "{{provisioner}}/{{workerType}} running"
    },
    {
     "expr": "sum by(workerType, provisioner) (tc_queue2_prometheus_quarantined_workers{provisioner=\"gecko-t\", workerType=\".*kvm.*\"})",
     "legendFormat": "{{provisioner}}/{{workerType}} quarantined"
    }
   ]
  },
  { "title": "Lag Alerts", "type": "alertlist", "gridPos": { "h": 10, "w": 15, "x": 9, "y": 39 } }
 ]
}