{
 "title": "Android - Meltdown Graphs",
 "tags": [
  "android",
  "android_meltdown_alerts",
  "owner=relsre"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Android Hardware (Bitbar)",
   "type": "timeseries",
   "description": "proj-autophone/gecko-t-ap-*",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "android_hw_total",
     "expr": "sum by() (tc_queue2_prometheus_pending_tasks{provisioner=\"proj-autophone\", workerType=~\".*bitbar.*\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "bitbar pending tasks",
     "query": "SELECT sum(\"value\") FROM \"bitbar_queue_size\" WHERE \"queue\" !~ /test/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Android Hardware (Lambda)",
   "type": "timeseries",
   "description": "proj-autophone/gecko-t-ap-*",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "android_hw_total",
     "expr": "sum by() (tc_queue2_prometheus_pending_tasks{provisioner=\"proj-autophone\", workerType=~\".*lambda.*\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "lambdatest pending tasks",
     "query": "SELECT sum(\"value\") FROM \"bitbar_queue_size\" WHERE \"queue\" !~ /test/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Android Emulated",
   "type": "timeseries",
   "description": "aws queue shows non-android work",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by() (tc_queue2_prometheus_pending_tasks{provisioner=\"gecko-t\", workerType=~\".*kvm.*\"})",
     "legendFormat": "total pending tasks"
    }
   ]
  }
 ]
}