{
 "title": "Android HW - Cluster Status",
 "tags": [
  "android_main_alerts",
  "android",
  "owner=relsre",
  "android_hw"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Bitbar Device Health Percentage",
   "type": "timeseries",
   "description": "working (non-problem) workers / configured workers",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "functioning worker %",
     "expr": "(sum by() (tc_android_prometheus_worker_health_configured_devices) - sum by() (tc_android_prometheus_worker_health_missing_or_offline_devices)) / sum by() (tc_android_prometheus_worker_health_configured_devices) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "health percentage",
     "measurement": "bitbar_workers",
     "query": "SELECT ((sum(\"configured\")- sum(\"problem\")) / sum(\"configured\")) * 100  FROM \"bitbar_workers\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "configured" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Device Health",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum by() (tc_android_prometheus_worker_health_configured_devices) - sum by() (tc_android_prometheus_worker_health_missing_or_offline_devices)) / sum by() (tc_android_prometheus_worker_health_configured_devices) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "query": "SELECT ((sum(\"configured\")- sum(\"problem\")) / sum(\"configured\")) * 100  FROM \"bitbar_workers\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "active vs configured proj-autophone workers",
   "type": "timeseries",
   "description": "all queues need to have work in order to reach full utilization (rarely the case). see link below.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (tc_android_prometheus_worker_health_configured_devices)",
     "legendFormat": "total configured workers"
    },
    {
     "expr": "sum by() (tc_queue2_prometheus_pending_tasks{provisioner=\"proj-autophone\"})",
     "legendFormat": "total pending tasks"
    }
   ]
  },
  {
   "title": "configured proj-autophone workers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_queue",
     "expr": "sum by () (tc_android_prometheus_worker_health_configured_devices)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "total workers",
     "measurement": "workers",
     "query": "SELECT max(\"configured\") FROM \"bitbar_workers\" WHERE (\"provisioner\" = 'proj-autophone') AND $timeFilter GROUP BY time($__interval), \"queue\" fill(none)\n",
     "select": [
      [
       { "params": [ "missing" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "$tag_queue",
     "expr": "tc_android_prometheus_worker_health_configured_devices",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "proj-autophone/{{workerType}} devices",
     "measurement": "workers",
     "query": "SELECT max(\"configured\") FROM \"bitbar_workers\" WHERE (\"provisioner\" = 'proj-autophone') AND $timeFilter GROUP BY time($__interval), \"queue\" fill(none)\n",
     "select": [
      [
       { "params": [ "missing" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "problem proj-autophone workers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_queue",
     "expr": "tc_android_prometheus_worker_health_missing_or_offline_devices",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "proj-autophone/{{workerType}}",
     "measurement": "bitbar_workers",
     "query": "SELECT sum(\"missing\") FROM \"workers\" WHERE $timeFilter GROUP BY time($__interval), \"queue\" fill(none)",
     "select": [
      [
       { "params": [ "problem" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "provisioner", "operator": "=", "value": "proj-autophone" },
      { "condition": "AND", "key": "queue", "operator": "!=", "value": "pixel2-unit-2" }
     ]
    }
   ]
  },
  {
   "title": "quarantined proj-autophone workers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by() (tc_queue2_prometheus_quarantined_workers{provisioner=\"proj-autophone\"})",
     "legendFormat": "total quarantined workers"
    },
    {
     "expr": "sum by(workerType) (tc_queue2_prometheus_quarantined_workers{provisioner=\"proj-autophone\"})",
     "legendFormat": "{{workerType}} quarantined workers"
    }
   ]
  },
  {
   "title": "total proj-autophone workers",
   "type": "timeseries",
   "description": "Queue keeps history of all workers for a duration of up to 5 days before they expire. So the actual number of currently active workers is likely different ",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (workerType)(\n  avg_over_time(\n    fxci_queue_workers_total{provisionerId=\"proj-autophone\"}[${__interval}]\n  )\n)\n",
     "legendFormat": "{{workerType}}"
    }
   ]
  }
 ]
}