{
 "title": "Android Queues",
 "tags": [
  "android_main_alerts",
  "android",
  "last_update=aerickson",
  "owner=relsre",
  "relsre-backup"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Android Hardware",
   "type": "timeseries",
   "description": "proj-autophone/gecko-t-ap-*",
   "gridPos": { "h": 14, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(tc_queue2_prometheus_pending_tasks{provisioner=\"proj-autophone\"})",
     "legendFormat": "total tasks"
    },
    {
     "expr": "tc_queue2_prometheus_pending_tasks{provisioner=\"proj-autophone\"}",
     "legendFormat": "{{provisioner}}/{{workerType}} pending tasks"
    }
   ]
  },
  {
   "title": "Android Hw Tasks",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tc_queue2_prometheus_pending_tasks{provisioner=\"proj-autophone\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Android Hw Health",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "((sum(tc_android_prometheus_worker_health_configured_devices) - sum(tc_android_prometheus_worker_health_missing_or_offline_devices)) / sum(tc_android_prometheus_worker_health_configured_devices)) * 100"
    }
   ]
  },
  {
   "title": "Android Emulated",
   "type": "timeseries",
   "description": "aws queue shows non-android work",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tc_queue2_prometheus_pending_tasks{provisioner=\"gecko-t\", workerType=~\".*kvm.*\"}",
     "legendFormat": "{{provisioner}}/{{workerType}} pending tasks"
    },
    {
     "expr": "tc_queue2_prometheus_running_workers{provisioner=\"gecko-t\", workerType=~\".*kvm.*\"}",
     "legendFormat": "{{provisioner}}/{{workerType}} running workers"
    }
   ]
  },
  {
   "title": "Android-Em Queue Tasks",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\ntc_queue2_prometheus_pending_tasks{provisioner=\"gecko-t\", workerType=~\".*kvm.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 16, "w": 7, "x": 0, "y": 21 } },
  { "title": "Lag Alerts", "type": "alertlist", "gridPos": { "h": 16, "w": 6, "x": 7, "y": 21 } },
  {
   "title": "Android Hw - Worker Details",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 21 },
   "targets": [
    {
     "expr": "sum by (\"workerType\") (tc_android_prometheus_worker_health_configured_devices)",
     "legendFormat": "configured"
    },
    {
     "expr": "sum by(workerType) (tc_android_prometheus_worker_health_missing_or_offline_devices)",
     "legendFormat": "missing or offline"
    },
    {
     "expr": "sum by(workerType) (tc_queue2_prometheus_running_workers{provisioner=\"proj-autophone\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum by(workerType) (tc_queue2_prometheus_quarantined_workers{provisioner=\"proj-autophone\"})",
     "legendFormat": "quarantined"
    }
   ]
  },
  {
   "title": "Android Em Workers",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 32 },
   "targets": [
    {
     "expr": "sum by(workerType) (tc_queue2_prometheus_running_workers{provisioner=\"gecko-t\", workerType=~\".*kvm.*\"})",
     "legendFormat": "{{workerType}} running"
    },
    {
     "expr": "sum by(workerType) (tc_queue2_prometheus_quarantined_workers{provisioner=\"gecko-t\", workerType=\".*kvm.*\"})",
     "legendFormat": "{{workerType}} quarantined"
    }
   ]
  }
 ]
}