{
 "title": "Workers",
 "tags": [
  "owner=relsre",
  "relsre-backup"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "provisioner",
    "query": {
     "query": "label_values(tc_queue2_prometheus_pending_tasks,provisioner)"
    }
   },
   {
    "name": "workerType",
    "query": {
     "query": "label_values(tc_queue2_prometheus_pending_tasks{provisioner=\"$provisioner\"},workerType)"
    }
   },
   { "name": "Adhoc" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Last Task Status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(provisioner, workerType) (tc_queue2_prometheus_exception_tasks{workerType!~\".*gcp.*\"})",
     "legendFormat": "{{provisioner}}/{{workerType}} exceptions"
    }
   ]
  },
  {
   "title": "Cloud",
   "type": "table",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum by(provisioner, workerType) (tc_queue2_prometheus_pending_tasks{\r\n    provisioner!~\"releng-hardware\",\r\n    provisioner!~\"proj-autophone\"\r\n})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(provisioner, workerType) (tc_queue2_prometheus_running_workers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TC Worker Backlog/Workers",
   "type": "timeseries",
   "description": "= Queued tasks / workers running tasks\nfiltered to:\nreleng-hardware\naws-provisioner-v1 with /^(mobile|app-services|gecko)-/\nterraform-packet",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(workerType, provisioner) (avg_over_time(tc_queue2_prometheus_pending_tasks{provisioner=~\"$provisioner\", workerType=~\"$workerType\"}[15m]) / avg_over_time(tc_queue2_prometheus_running_workers{provisioner=~\"$provisioner\", workerType=~\"$workerType\"}[15m]))",
     "legendFormat": "{{provisioner}}/{{workerType}} runner load"
    }
   ]
  },
  {
   "title": "Workers vs Active",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(provisioner, workerType) (\n  avg_over_time(tc_queue2_prometheus_running_workers{\n    provisioner!~\"^gecko.*\",\n    provisioner!~\".*k8s\",\n    provisioner=~\"$provisioner\", \n    workerType=~\"$workerType\",\n  }[$__interval])\n) ",
     "legendFormat": "{{provisioner}}/{{workerType}} active"
    },
    {
     "expr": "sum by(provisioner, workerType) (\n  avg_over_time(tc_queue2_prometheus_workers_total{\n    provisioner!~\"^gecko.*\",\n    provisioner!~\".*k8s\",\n    provisioner=~\"$provisioner\", \n    workerType=~\"$workerType\", \n  }[$__interval])\n  - \n  avg_over_time(tc_queue2_prometheus_quarantined_workers{\n    provisioner!~\"^gecko.*\",\n    provisioner!~\".*k8s\",\n    provisioner=~\"$provisioner\", \n    workerType=~\"$workerType\", \n  }[$__interval])\n) ",
     "legendFormat": "{{provisioner}}/{{workerType}} workers"
    },
    {
     "expr": "sum by(provisioner, workerType) (\n  avg_over_time(tc_queue2_prometheus_quarantined_workers{\n    provisioner!~\"^gecko.*\",\n    provisioner!~\"k8s\",\n    provisioner=~\"$provisioner\", \n    workerType=~\"$workerType\", \n  }[$__interval])\n) ",
     "legendFormat": "{{provisioner}}/{{workerType}} quarantined"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "timeseries",
   "description": "<https://wiki.mozilla.org/CIDuty/How_To/High_Pending_Counts>",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(workerType, provisioner) (tc_queue2_prometheus_pending_tasks{provisioner=~\"$provisioner\", workerType=~\"$workerType\"})",
     "legendFormat": "{{provisioner}}/{{workerType}}  queue"
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "table",
   "description": "Only shows queue with > 0",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(provisioner, workerType) (tc_queue2_prometheus_pending_tasks{\r\n    provisioner=~\"^(releng-hardware|bitbar|proj-autophone)$\"\r\n})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(provisioner, workerType) (tc_queue2_prometheus_running_workers)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(provisioner, workerType) (tc_web_prometheus_taskcluster_idle_workers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active vs Queue",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(tc_web_prometheus_taskcluster_running_workers{provisionerId=~\"^(bitbar|gecko-1|gecko-2|gecko-3|gecko-t|mobile-1|mobile-3|proj-autophone|releng-hardware|scriptworker-k8s|scriptworker-prov-v1)$\", workerType=~\".*\"}[10m])",
     "legendFormat": "{{workerType}}"
    },
    {
     "expr": "avg_over_time(tc_web_prometheus_taskcluster_pending_tasks{provisionerId=~\"^(bitbar|gecko-1|gecko-2|gecko-3|gecko-t|mobile-1|mobile-3|proj-autophone|releng-hardware|scriptworker-k8s|scriptworker-prov-v1)$\", workerType=~\".*\"}[1m])",
     "legendFormat": "{{workerType}}"
    }
   ]
  },
  {
   "title": "Active vs Queue",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(tc_web_prometheus_taskcluster_running_workers{provisionerId=~\"^(bitbar|gecko-1|gecko-2|gecko-3|gecko-t|mobile-1|mobile-3|proj-autophone|releng-hardware|scriptworker-k8s|scriptworker-prov-v1)$\", workerType=~\".*\"}[10m])",
     "legendFormat": "{{workerType}}"
    },
    {
     "expr": "avg_over_time(tc_web_prometheus_taskcluster_pending_tasks{provisionerId=~\"^(bitbar|gecko-1|gecko-2|gecko-3|gecko-t|mobile-1|mobile-3|proj-autophone|releng-hardware|scriptworker-k8s|scriptworker-prov-v1)$\", workerType=~\".*\"}[1m])",
     "legendFormat": "{{workerType}}"
    }
   ]
  }
 ]
}