{
 "title": "All Devices Status",
 "tags": [
  "status",
  "all-devices"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host_re", "label": "Host regex", "query": ".*" },
   {
    "name": "worker_pool_id",
    "label": "Worker Pool",
    "query": {
     "query": "from(bucket: \"marlin-icinga2\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r._measurement == \"nrpe\")\n  |> filter(fn: (r) => r.service == \"Windows Worker Pool ID\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.hostname =~ /${host_re}/)\n  |> group(columns: [\"hostname\"])\n  |> last()\n  |> keep(columns: [\"_value\"])\n  |> group()\n  |> distinct(column: \"_value\")\n  |> sort(columns: [\"_value\"])"
    }
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nall_hosts =\n  schema.tagValues(\n    bucket: \"marlin-icinga2\",\n    tag: \"hostname\",\n    predicate: (r) =>\n      r._measurement == \"hostalive\" and\n      r.hostname =~ /${host_re}/\n  )\n    |> rename(columns: {_value: \"hostname\"})\n    |> map(fn: (r) => ({ hostname: r.hostname, worker_pool_id: \"zzz-no-pool\" }))\n\npool_hosts =\n  from(bucket: \"marlin-icinga2\")\n    |> range(start: -7d)\n    |> filter(fn: (r) => r._measurement == \"nrpe\")\n    |> filter(fn: (r) => r.service == \"Windows Worker Pool ID\")\n    |> filter(fn: (r) => r._field == \"value\")\n    |> filter(fn: (r) => r.hostname =~ /${host_re}/)\n    |> group(columns: [\"hostname\"])\n    |> last()\n    |> keep(columns: [\"hostname\", \"_value\"])\n    |> rename(columns: {_value: \"worker_pool_id\"})\n\nunion(tables: [all_hosts, pool_hosts])\n  |> group(columns: [\"hostname\"])\n  |> sort(columns: [\"worker_pool_id\"])\n  |> limit(n: 1)\n  |> filter(fn: (r) => r.worker_pool_id =~ /^(${worker_pool_id:regex})$/)\n  |> group()\n  |> sort(columns: [\"worker_pool_id\", \"hostname\"])\n  |> rename(columns: {hostname: \"_value\"})\n  |> keep(columns: [\"_value\"])"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Windows Devices",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"marlin-icinga2\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"hostalive\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.hostname =~ /${host_re}/)\n  |> filter(fn: (r) => r.hostname =~ /nuc/ or r.hostname =~ /^t-w/)\n  |> group(columns: [\"hostname\"])\n  |> last()\n  |> group()\n  |> count(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Linux Devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"marlin-icinga2\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"hostalive\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.hostname =~ /${host_re}/)\n  |> filter(fn: (r) => r.hostname =~ /linux/)\n  |> group(columns: [\"hostname\"])\n  |> last()\n  |> group()\n  |> count(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Mac Devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"marlin-icinga2\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"hostalive\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.hostname =~ /${host_re}/)\n  |> filter(fn: (r) => r.hostname =~ /mac/ or r.hostname =~ /mojave/)\n  |> group(columns: [\"hostname\"])\n  |> last()\n  |> group()\n  |> count(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Unknown Devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"marlin-icinga2\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r._measurement == \"hostalive\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.hostname =~ /${host_re}/)\n  |> filter(fn: (r) => not (r.hostname =~ /nuc/ or r.hostname =~ /^t-w/) and not r.hostname =~ /linux/ and not (r.hostname =~ /mac/ or r.hostname =~ /mojave/))\n  |> group(columns: [\"hostname\"])\n  |> last()\n  |> group()\n  |> count(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Windows",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"marlin-icinga2\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"hostalive\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.hostname =~ /^${hostname:regex}$/)\n  |> filter(fn: (r) => r.hostname =~ /nuc/ or r.hostname =~ /^t-w/)\n  |> group(columns: [\"hostname\"])\n  |> last()\n  |> keep(columns: [\"hostname\", \"_value\", \"_time\"])\n  |> rename(columns: {_value: \"status\"})\n  |> group()"
    },
    {
     "query": "from(bucket: \"marlin-icinga2\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r._measurement == \"nrpe\")\n  |> filter(fn: (r) => r.service == \"Windows Worker Pool ID\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.hostname =~ /^${hostname:regex}$/)\n  |> filter(fn: (r) => r.hostname =~ /nuc/ or r.hostname =~ /^t-w/)\n  |> group(columns: [\"hostname\"])\n  |> last()\n  |> keep(columns: [\"hostname\", \"_value\"])\n  |> rename(columns: {_value: \"pool\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Linux",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"marlin-icinga2\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"hostalive\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.hostname =~ /^${hostname:regex}$/)\n  |> filter(fn: (r) => r.hostname =~ /linux/)\n  |> group(columns: [\"hostname\"])\n  |> last()\n  |> keep(columns: [\"hostname\", \"_value\", \"_time\"])\n  |> rename(columns: {_value: \"status\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Mac",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"marlin-icinga2\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"hostalive\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.hostname =~ /^${hostname:regex}$/)\n  |> filter(fn: (r) => r.hostname =~ /mac/ or r.hostname =~ /mojave/)\n  |> group(columns: [\"hostname\"])\n  |> last()\n  |> keep(columns: [\"hostname\", \"_value\", \"_time\"])\n  |> rename(columns: {_value: \"status\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Unknown",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "from(bucket: \"marlin-icinga2\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"hostalive\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.hostname =~ /^${hostname:regex}$/)\n  |> filter(fn: (r) => not (r.hostname =~ /nuc/ or r.hostname =~ /^t-w/) and not r.hostname =~ /linux/ and not (r.hostname =~ /mac/ or r.hostname =~ /mojave/))\n  |> group(columns: [\"hostname\"])\n  |> last()\n  |> keep(columns: [\"hostname\", \"_value\", \"_time\"])\n  |> rename(columns: {_value: \"status\"})\n  |> group()"
    }
   ]
  }
 ]
}