{
 "title": "Workers",
 "tags": [
  "owner=relsre",
  "relsre-backup",
  "relsre-development",
  "taskcluster-metrics"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "provisioner",
    "query": {
     "query": "label_values(fxci_queue_pending_tasks, provisionerId)"
    }
   },
   {
    "name": "workerType",
    "query": {
     "query": "label_values(fxci_queue_pending_tasks{provisionerId=~\"$provisioner\"}, workerType)"
    }
   },
   { "name": "Adhoc" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Last Task Status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(provisionerId, workerType) (increase(fxci_queue_exception_tasks{provisionerId=~\"$provisioner\", workerType=~\"$workerType\", workerType!~\".*gcp.*\"}[15m]))",
     "legendFormat": "{{provisionerId}}/{{workerType}} exceptions"
    },
    {
     "expr": "sum by(provisionerId, workerType) (increase(fxci_queue_completed_tasks{provisionerId=~\"$provisioner\", workerType=~\"$workerType\", workerType!~\".*gcp.*\"}[15m]))",
     "legendFormat": "{{provisionerId}}/{{workerType}} completed"
    }
   ]
  },
  {
   "title": "Cloud",
   "type": "table",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum by(provisioner, workerType) (label_replace(fxci_queue_pending_tasks{provisionerId!~\"^(releng-hardware|proj-autophone|scriptworker-prov-v1)\", provisionerId=~\"$provisioner\", workerType=~\"$workerType\"}, \"provisioner\", \"$1\", \"provisionerId\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(provisioner, workerType) (label_replace(fxci_queue_running_workers{provisionerId!~\"^(releng-hardware|proj-autophone|scriptworker-prov-v1)\", provisionerId=~\"$provisioner\", workerType=~\"$workerType\"}, \"provisioner\", \"$1\", \"provisionerId\", \"(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TC Worker Backlog/Workers",
   "type": "timeseries",
   "description": "= Queued tasks / workers running tasks\nfiltered to:\nreleng-hardware\naws-provisioner-v1 with /^(mobile|app-services|gecko)-/\nterraform-packet",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(workerType, provisionerId) (avg_over_time(fxci_queue_pending_tasks{provisionerId=~\"$provisioner\", workerType=~\"$workerType\"}[15m]) / avg_over_time(fxci_queue_running_workers{provisionerId=~\"$provisioner\", workerType=~\"$workerType\"}[15m]))",
     "legendFormat": "{{provisionerId}}/{{workerType}} load"
    }
   ]
  },
  {
   "title": "Workers vs Active",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(provisionerId, workerType) (\n  avg_over_time(fxci_queue_running_workers{\n    provisionerId!~\"^gecko.*\",\n    provisionerId!~\".*k8s\",\n    provisionerId=~\"$provisioner\",\n    workerType=~\"$workerType\",\n  }[$__interval])\n) ",
     "legendFormat": "{{provisionerId}}/{{workerType}} active"
    },
    {
     "expr": "sum by(provisionerId, workerType) (\n  avg_over_time(fxci_queue_workers_total{\n    provisionerId!~\"^gecko.*\",\n    provisionerId!~\".*k8s\",\n    provisionerId=~\"$provisioner\",\n    workerType=~\"$workerType\",\n  }[$__interval])\n  - \n  avg_over_time(fxci_queue_quarantined_workers{\n    provisionerId!~\"^gecko.*\",\n    provisionerId!~\".*k8s\",\n    provisionerId=~\"$provisioner\",\n    workerType=~\"$workerType\",\n  }[$__interval])\n) ",
     "legendFormat": "{{provisionerId}}/{{workerType}} workers"
    },
    {
     "expr": "sum by(provisionerId, workerType) (\n  avg_over_time(fxci_queue_quarantined_workers{\n    provisionerId!~\"^gecko.*\",\n    provisionerId!~\"k8s\",\n    provisionerId=~\"$provisioner\",\n    workerType=~\"$workerType\",\n  }[$__interval])\n) ",
     "legendFormat": "{{provisionerId}}/{{workerType}} quarantined"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "timeseries",
   "description": "<https://wiki.mozilla.org/CIDuty/How_To/High_Pending_Counts>",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(workerType, provisionerId) (fxci_queue_pending_tasks{provisionerId=~\"$provisioner\", workerType=~\"$workerType\"})",
     "legendFormat": "{{provisionerId}}/{{workerType}}  queue"
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "table",
   "description": "Only shows queue with > 0",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(provisioner, workerType) (label_replace(fxci_queue_pending_tasks{provisionerId=~\"$provisioner\", workerType=~\"$workerType\", provisionerId=~\"^(releng-hardware|bitbar|proj-autophone)$\"}, \"provisioner\", \"$1\", \"provisionerId\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(provisioner, workerType) (label_replace(fxci_queue_running_workers{provisionerId=~\"$provisioner\", workerType=~\"$workerType\", provisionerId=~\"^(releng-hardware|bitbar|proj-autophone)$\"}, \"provisioner\", \"$1\", \"provisionerId\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(provisioner, workerType) (label_replace(fxci_queue_idle_workers{provisionerId=~\"$provisioner\", workerType=~\"$workerType\", provisionerId=~\"^(releng-hardware|bitbar|proj-autophone)$\"}, \"provisioner\", \"$1\", \"provisionerId\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(provisioner, workerType) (label_replace(fxci_queue_workers_total{provisionerId=~\"$provisioner\", workerType=~\"$workerType\", provisionerId=~\"^(releng-hardware|bitbar|proj-autophone)$\"}, \"provisioner\", \"$1\", \"provisionerId\", \"(.*)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by(provisioner, workerType) (label_replace(fxci_queue_quarantined_workers{provisionerId=~\"$provisioner\", workerType=~\"$workerType\", provisionerId=~\"^(releng-hardware|bitbar|proj-autophone)$\"}, \"provisioner\", \"$1\", \"provisionerId\", \"(.*)\")) / sum by(provisioner, workerType) (label_replace(fxci_queue_workers_total{provisionerId=~\"$provisioner\", workerType=~\"$workerType\", provisionerId=~\"^(releng-hardware|bitbar|proj-autophone)$\"}, \"provisioner\", \"$1\", \"provisionerId\", \"(.*)\")) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active vs Queue",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(fxci_queue_running_workers{provisionerId=~\"$provisioner\", workerType=~\"$workerType\"}[10m])",
     "legendFormat": "{{workerType}} active"
    },
    {
     "expr": "avg_over_time(fxci_queue_pending_tasks{provisionerId=~\"$provisioner\", workerType=~\"$workerType\"}[1m])",
     "legendFormat": "{{workerType}} queue"
    }
   ]
  },
  {
   "title": "Active vs Queue",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(fxci_queue_running_workers{provisionerId=~\"$provisioner\", workerType=~\"$workerType\"}[10m])",
     "legendFormat": "{{provisionerId}}/{{workerType}} active"
    },
    {
     "expr": "avg_over_time(fxci_queue_pending_tasks{provisionerId=~\"$provisioner\", workerType=~\"$workerType\"}[1m])",
     "legendFormat": "{{provisionerId}}/{{workerType}} queue"
    }
   ]
  }
 ]
}