{
 "title": "Android Queues",
 "tags": [
  "android",
  "hardware"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Android Hardware (Bitbar)",
   "type": "graph",
   "description": "proj-autophone/gecko-t-ap-*",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "jobs" }
   ],
   "targets": [
    {
     "alias": "proj-autophone/$tag_queue",
     "groupBy": [
      { "params": [ "queue" ], "type": "tag" }
     ],
     "measurement": "current",
     "query": "SELECT * FROM \"bitbar_queue_size\" WHERE $timeFilter GROUP BY \"queue\";\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "queue", "operator": "=", "value": "gecko-t-ap-batt-g5" }
     ]
    },
    {
     "alias": "android_hw_total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\")  FROM \"bitbar_queue_size\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Android-HW Jobs",
   "type": "singlestat",
   "description": "all queues",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bitbar_queue_size",
     "query": "SELECT sum(\"value\") FROM \"bitbar_queue_size\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Android Emulated (AWS and Packet)",
   "type": "graph",
   "description": "aws queue shows non-android work",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "jobs" }
   ],
   "targets": [
    {
     "alias": "$tag_provisionerId/$tag_workerType (4.3)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"pendingTasks\" FROM \"tc_queue_exec\" WHERE (\"provisionerId\" = 'aws-provisioner-v1' AND \"workerType\" = 'gecko-t-linux-xlarge') AND $timeFilter GROUP BY \"workerType\", \"provisionerId\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_provisionerId/$tag_workerType (7.0)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"pendingTasks\" FROM \"tc_queue_exec\" WHERE (\"provisionerId\" = 'terraform-packet' AND \"workerType\" = 'gecko-t-linux') AND $timeFilter GROUP BY \"workerType\", \"provisionerId\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Android-Em Packet.net Jobs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"pendingTasks\" FROM \"tc_queue_exec\" WHERE (\"provisionerId\" = 'terraform-packet' AND \"workerType\" = 'gecko-t-linux') AND $timeFilter GROUP BY \"workerType\", \"provisionerId\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 19, "x": 0, "y": 16 } }
 ]
}