{
 "title": "Hardware Workers",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "platform", "query": "W10,linux,yosemite" },
   { "name": "filter" },
   { "name": "alert_filter", "label": "alert filter" }
  ]
 },
 "panels": [
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queued",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pending $tag_workerType",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/pending/" }
     ]
    }
   ]
  },
  {
   "title": "Started",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "started",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/^task start/" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "task error",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/^task error/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$platform/" }
     ]
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Dead Worker Alerts",
   "type": "table",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "alerts",
     "query": "SELECT last(\"duration\") /(1000*1000*1000*60) AS \"duration\", last(\"message\"), last(\"value\") AS \"log messages\" FROM \"autogen\".\"alerts\" WHERE (\"alertName\" = 'RelOps deadman workers' AND \"host\" =~ /$platform/) AND $timeFilter GROUP BY \"host\" ORDER BY time DESC",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "duration" ], "type": "alias" }
      ],
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "message" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "log messages" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "alertName", "operator": "=", "value": "RelOps deadman workers" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$platform/" }
     ]
    }
   ]
  },
  {
   "title": "$platform",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "repeat": "platform",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_level",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "alerts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "alertName", "operator": "=", "value": "RelOps deadman workers" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$platform/" }
     ]
    }
   ]
  },
  {
   "title": "$platform",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_level",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "alerts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "alertName", "operator": "=", "value": "RelOps deadman workers" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$platform/" }
     ]
    }
   ]
  },
  {
   "title": "Task Errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "papertrail",
     "query": "SELECT mean(\"count\") FROM \"autogen\".\"papertrail\" WHERE (\"event\" = 'task error') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "slimit": "200",
     "tags": [
      { "key": "event", "operator": "=", "value": "task error" }
     ]
    }
   ]
  },
  {
   "title": "$platform",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_level",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "alerts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "alertName", "operator": "=", "value": "RelOps deadman workers" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$platform/" }
     ]
    }
   ]
  },
  {
   "title": "DeployStudio Workflow Execution",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "alias": "[[tag_host]]",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "deploystudio workflow" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "new host puppet run" }
     ]
    }
   ]
  },
  { "title": "VCS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Tree status",
   "type": "table",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 45 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo" ], "type": "tag" },
      { "params": [ "reason" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "who" ], "type": "tag" }
     ],
     "measurement": "treestatus_stack_exec",
     "query": "SELECT \"status_value\" FROM \"autogen\".\"treestatus_stack_exec\" WHERE (\"repo\" =~ /mozilla-[ribc]|^try$|^autoland$/ AND \"status\" = 'closed') AND $timeFilter GROUP BY \"repo\", \"reason\", \"status\", \"who\"",
     "select": [
      [
       { "params": [ "status_value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "repo",
       "operator": "=~",
       "value": "/mozilla-[ribc]|^try$|^autoland$/"
      },
      { "condition": "AND", "key": "status", "operator": "=", "value": "closed" }
     ]
    }
   ]
  }
 ]
}