{
 "title": "aerickson sandbox 2",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "g5 perf",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "taskcluster_workertype_tasks",
     "select": [
      [
       { "params": [ "concurrent" ], "type": "field" }
      ],
      [
       { "params": [ "defined" ], "type": "field" }
      ],
      [
       { "params": [ "pending" ], "type": "field" }
      ],
      [
       { "params": [ "running" ], "type": "field" }
      ],
      [
       { "params": [ "completed" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ],
      [
       { "params": [ "exception" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=", "value": "dev" },
      { "condition": "AND", "key": "workertype", "operator": "=", "value": "gecko-t-bitbar-gw-perf-g5" }
     ]
    }
   ]
  },
  {
   "title": "gw-perf-g5 Active vs Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_web_exec",
     "select": [
      [
       { "params": [ "runningWorkers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "proj-autophone" },
      { "condition": "AND", "key": "workerType", "operator": "=", "value": "gecko-t-bitbar-gw-perf-g5" }
     ]
    },
    {
     "alias": "$tag_workerType $col mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "proj-autophone" },
      { "condition": "AND", "key": "workerType", "operator": "=", "value": "gecko-t-bitbar-gw-perf-g5" }
     ]
    }
   ]
  },
  {
   "title": "p2 perf",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "taskcluster_workertype_tasks",
     "select": [
      [
       { "params": [ "concurrent" ], "type": "field" }
      ],
      [
       { "params": [ "defined" ], "type": "field" }
      ],
      [
       { "params": [ "pending" ], "type": "field" }
      ],
      [
       { "params": [ "running" ], "type": "field" }
      ],
      [
       { "params": [ "completed" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ],
      [
       { "params": [ "exception" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=", "value": "dev" },
      { "condition": "AND", "key": "workertype", "operator": "=", "value": "gecko-t-bitbar-gw-perf-p2" }
     ]
    }
   ]
  },
  {
   "title": "gw-perf-p2 Active vs Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_web_exec",
     "select": [
      [
       { "params": [ "runningWorkers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "proj-autophone" },
      { "condition": "AND", "key": "workerType", "operator": "=", "value": "gecko-t-bitbar-gw-perf-p2" }
     ]
    },
    {
     "alias": "$tag_workerType $col mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "proj-autophone" },
      { "condition": "AND", "key": "workerType", "operator": "=", "value": "gecko-t-bitbar-gw-perf-p2" }
     ]
    }
   ]
  },
  {
   "title": "Cluster Active vs Configured",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "configured",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bitbar_workers",
     "query": "SELECT sum(\"configured\") FROM \"bitbar_workers\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "configured" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"runningWorkers\") AS \"active\" FROM \"tc_web_exec\" WHERE (\"provisionerId\" = 'proj-autophone') AND $timeFilter GROUP BY time($__interval * 10), \"provisionerId\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "gw-unit-p2 Active vs Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_web_exec",
     "select": [
      [
       { "params": [ "runningWorkers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "proj-autophone" },
      { "condition": "AND", "key": "workerType", "operator": "=", "value": "gecko-t-bitbar-gw-unit-p2" }
     ]
    },
    {
     "alias": "$tag_workerType $col mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "proj-autophone" },
      { "condition": "AND", "key": "workerType", "operator": "=", "value": "gecko-t-bitbar-gw-unit-p2" }
     ]
    }
   ]
  }
 ]
}