{
 "title": "Alerts",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queued Load (releng-hardware)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_provisionerId/$tag_workerType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^tc_queue/",
     "query": "SELECT max(\"queued_load\") FROM (SELECT mean(\"queue\") / mean(\"running\") AS \"queued_load\" FROM (SELECT mean(\"pendingTasks\") AS \"queue\", mean(\"running\") AS \"running\" FROM /^tc_queue2/ WHERE $timeFilter AND \"provisionerId\" = 'releng-hardware' GROUP BY time($__interval), \"provisionerId\", \"workerType\", \"workerGroup\" fill(previous)) GROUP BY time($__interval), \"provisionerId\", \"workerType\", \"workerGroup\")  GROUP BY time($__interval), \"provisionerId\", \"workerType\", \"workerGroup\"",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "running" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "MacOS Builder/PGO Queued Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT min(\"pendingTasks\") / min(\"running\") FROM \"tc_queue2_exec\" WHERE (\"workerType\" = 'gecko-3-b-osx-1015') AND $timeFilter GROUP BY \"workerType\", time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=", "value": "gecko-3-b-osx-1015" }
     ]
    },
    {
     "alias": "$tag_workerType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT min(\"workers\") FROM \"tc_queue2_exec\" WHERE (\"workerType\" = 'gecko-3-b-osx-1015') AND $timeFilter GROUP BY \"workerType\", time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=", "value": "gecko-3-b-osx-1015" }
     ]
    }
   ]
  },
  {
   "title": "Exception on gecko-3",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_provisionerId $tag_workerType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^tc_queue/",
     "select": [
      [
       { "params": [ "exception" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^gecko-3/" }
     ]
    }
   ]
  },
  {
   "title": "MacOS Power test Queued Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT min(\"pendingTasks\") / min(\"running\") FROM \"tc_queue2_exec\" WHERE (\"workerType\" = 'gecko-t-osx-1014-power') AND $timeFilter GROUP BY \"workerType\", time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=", "value": "gecko-3-b-osx-1015" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "select": [
      [
       { "params": [ "workers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=", "value": "gecko-t-osx-1014-power" }
     ]
    }
   ]
  },
  {
   "title": "Queued Tasks (not releng-hardware)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $tag_provisionerId",
     "groupBy": [
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT * FROM \"bitbar_queue_size\" WHERE $timeFilter AND queue =~ /^$queue$/  GROUP BY \"queue\";\n",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "!=", "value": "releng-hardware" }
     ]
    },
    {
     "alias": "$tag_provisionerId total",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "provisionerId" ], "type": "tag" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT * FROM \"bitbar_queue_size\" WHERE $timeFilter AND queue =~ /^$queue$/  GROUP BY \"queue\";\n",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "!=", "value": "releng-hardware" }
     ]
    }
   ]
  },
  {
   "title": "Worker State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Worker Panic [69]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Hardware",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "Exit code 69" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
     ]
    },
    {
     "alias": "Non-datacenter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "Exit code 69" },
      { "condition": "AND", "key": "host", "operator": "!~", "value": "/mdc[0-9].mozilla.com$/" }
     ]
    }
   ]
  },
  {
   "title": "Datacenter Worker Panic [69]",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "Exit code 69" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
     ]
    }
   ]
  },
  {
   "title": "TC cache failure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_event",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT sum(\"count\") FROM \"papertrail\" WHERE (\"event\" = 'Not able to rename dir' OR \"event\" = 'file-missing-on-worker') AND $timeFilter GROUP BY \"host\", \"event\", time(10m) fill(linear) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "Not able to rename dir" },
      { "condition": "OR", "key": "event", "operator": "=", "value": "file-missing-on-worker" }
     ]
    }
   ]
  },
  {
   "title": "Moonshot worker counts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT (max(\"workers\") - max(\"quarantined\")) AS \"workers\" FROM \"tc_queue2_exec\" WHERE \"provisionerId\" = 'releng-hardware' AND \"workerType\" =~  /^(gecko-t-linux-talos|gecko-t-linux-talos-1804|gecko-t-linux-talos-1804-dev|gecko-t-win10-64-1803-hw|gecko-t-win10-64-hw)$/ AND $timeFilter GROUP BY time(1h), \"workerType\" fill(previous)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "workers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "running" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" },
      { "condition": "AND", "key": "provisionerId", "operator": "=", "value": "releng-hardware" }
     ]
    }
   ]
  },
  {
   "title": "MacOS Build+PGO Worker Logging",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "macmini-r8 logging",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT count(\"mean\") FROM (SELECT mean(\"count\") FROM \"papertrail\" WHERE \"host\" =~ /^macmini-r8/ AND $timeFilter GROUP BY \"host\", time($__interval) fill(linear)) GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "workers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=", "value": "gecko-3-t-osx-1014" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "t-mojave-r7-471" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "t-mojave" }
     ]
    }
   ]
  },
  {
   "title": "Mac Signing Logs",
   "type": "graph",
   "description": "Primarily logins.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "mac-signing",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT count(\"mean\") FROM (SELECT mean(\"count\") FROM \"papertrail\" WHERE \"host\" =~ /mac-v3-signing.*/ AND $timeFilter GROUP BY \"host\", time($__interval) fill(linear)) GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "workers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=", "value": "gecko-3-t-osx-1014" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "t-mojave-r7-471" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "t-mojave" }
     ]
    },
    {
     "alias": "dep-mac-signing",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT count(\"mean\") FROM (SELECT mean(\"count\") FROM \"papertrail\" WHERE \"host\" =~ /dep-mac-v3-signing.*/ AND $timeFilter GROUP BY \"host\", time($__interval) fill(linear)) GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "workers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=", "value": "gecko-3-t-osx-1014" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "t-mojave-r7-471" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "t-mojave" }
     ]
    },
    {
     "alias": "tb-mac-signing",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT count(\"mean\") FROM (SELECT mean(\"count\") FROM \"papertrail\" WHERE \"host\" =~ /tb-mac-v3-signing.*/ AND $timeFilter GROUP BY \"host\", time($__interval) fill(linear)) GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "workers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=", "value": "gecko-3-t-osx-1014" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "t-mojave-r7-471" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "t-mojave" }
     ]
    }
   ]
  },
  {
   "title": "Mac worker counts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT (max(\"workers\") - max(\"quarantined\")) AS \"workers\" FROM \"tc_queue2_exec\" WHERE \"provisionerId\" = 'releng-hardware' AND \"workerType\" =~  /^gecko-.*osx.*/ AND $timeFilter GROUP BY time(1h), \"workerType\" fill(previous)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "workers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "running" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" },
      { "condition": "AND", "key": "provisionerId", "operator": "=", "value": "releng-hardware" }
     ]
    }
   ]
  },
  {
   "title": "Count of logging hosts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "1h",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT count(count) FROM (SELECT count(\"count\") AS count FROM \"six_month\".\"papertrail\" WHERE (\"event\" = 'space') AND (time > now() - 12h) GROUP BY \"host\", time(1h)) GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "space" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "space" }
     ]
    }
   ]
  },
  {
   "title": "M1 x86 processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_basename (expected)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"arch\") FROM \"worker.arch\" WHERE (\"arch\" = 'x86_64') AND (\"basename\" = 'node' OR \"basename\" = 'js' OR \"basename\" = 'minidump_stackwalk' OR \"basename\" = 'minidump-stackwalk') AND $timeFilter GROUP BY time($interval), \"basename\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_basename",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"arch\") FROM \"worker.arch\" WHERE (\"arch\" = 'x86_64') AND $timeFilter AND (\"basename\" != 'node' AND \"basename\" != 'js' AND \"basename\" != 'minidump_stackwalk' AND \"basename\" != 'minidump-stackwalk') GROUP BY time($interval), \"basename\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hardware State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Moonshot repeat hung",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_chassis $tag_cart : $tag_workerId",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "chassis" ], "type": "tag" },
      { "params": [ "cart" ], "type": "tag" },
      { "params": [ "workerId" ], "type": "tag" }
     ],
     "measurement": "systemcheck",
     "select": [
      [
       { "params": [ "missing" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "no ping" ], "type": "alias" }
      ],
      [
       { "params": [ "hung" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "hung" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "hung" }
     ]
    }
   ]
  },
  {
   "title": "Disk Space (Builders/PGO)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_workerId disk gb",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "workerId" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "/1073741824" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^disk[01]/" },
      {
       "condition": "AND",
       "key": "workerId",
       "operator": "=~",
       "value": "/^macmini-r8-(138|139|195|196|197|198|199|200)/"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_workerId disk gb",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "workerId" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "/1073741824" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^disk[01]/" },
      {
       "condition": "AND",
       "key": "workerId",
       "operator": "!~",
       "value": "/^macmini-r8-(138|139|195|196|197|198|199|200)/"
      }
     ]
    }
   ]
  },
  {
   "title": "Moonshot repeat missing",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_chassis $tag_cart : $tag_workerId",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "chassis" ], "type": "tag" },
      { "params": [ "cart" ], "type": "tag" },
      { "params": [ "workerId" ], "type": "tag" }
     ],
     "measurement": "systemcheck",
     "select": [
      [
       { "params": [ "missing" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "no ping" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "missing" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "description": "Top(10) CPU Temperature C",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerId",
     "groupBy": [
      { "params": [ "$__interval * 100" ], "type": "time" },
      { "params": [ "workerId" ], "type": "tag" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "thermal",
     "select": [
      [
       { "params": [ "machdep.xcpm.cpu_thermal_level" ], "type": "field" },
       { "params": [ "10" ], "type": "top" },
       { "params": [ "temp max" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Moonshot Power Error",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval * 20" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT mean(\"count\") FROM \"papertrail\" WHERE (\"event\" = 'Moonshot Power Error') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "Moonshot Power Error" }
     ]
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $tag_provisionerId",
     "groupBy": [
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT * FROM \"bitbar_queue_size\" WHERE $timeFilter AND queue =~ /^$queue$/  GROUP BY \"queue\";\n",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "workerType",
       "operator": "=~",
       "value": "/^gecko-t-(linux|osx|win).*(large|talos|hw|1014)$/"
      }
     ]
    },
    {
     "alias": "$tag_provisionerId total",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "provisionerId" ], "type": "tag" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT * FROM \"bitbar_queue_size\" WHERE $timeFilter AND queue =~ /^$queue$/  GROUP BY \"queue\";\n",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^gecko-[0-9]-b/" }
     ]
    }
   ]
  },
  {
   "title": "Software releases",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_platform $tag_package $tag_channel $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "package" ], "type": "tag" },
      { "params": [ "platform" ], "type": "tag" }
     ],
     "measurement": "releases",
     "select": [
      [
       { "params": [ "version" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Software releases",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "alias": "$tag_platform $tag_package $tag_channel $col",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "package" ], "type": "tag" },
      { "params": [ "platform" ], "type": "tag" }
     ],
     "measurement": "releases",
     "select": [
      [
       { "params": [ "version" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GCP Queued Load - gecko-{t,3}/t-linux-xlarge",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_provisionerId/$tag_workerType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^tc_queue/",
     "query": "SELECT max(\"queued_load\") FROM (SELECT mean(\"queue\") / mean(\"running\") AS \"queued_load\" FROM (SELECT mean(\"pendingTasks\") AS \"queue\", mean(\"running\") AS \"running\" FROM /^tc_queue2/ WHERE $timeFilter AND (\"provisionerId\" = 'gecko-t' AND \"workerType\" = 't-linux-xlarge') OR (\"provisionerId\" = 'gecko-3' AND \"workerType\" = 't-linux-xlarge') GROUP BY time($__interval), \"provisionerId\", \"workerType\", \"workerGroup\" fill(previous)) GROUP BY time($__interval), \"provisionerId\", \"workerType\", \"workerGroup\")  GROUP BY time($__interval), \"provisionerId\", \"workerType\", \"workerGroup\"",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "running" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col $tag_provisionerId/$tag_workerType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/^tc_queue/",
     "query": "SELECT mean(\"pendingTasks\") AS \"queue\", mean(\"running\") AS \"running\" FROM /^tc_queue2/ WHERE $timeFilter AND (\"provisionerId\" = 'gecko-t' AND \"workerType\" = 't-linux-xlarge') OR (\"provisionerId\" = 'gecko-3' AND \"workerType\" = 't-linux-xlarge') GROUP BY time($__interval), \"provisionerId\", \"workerType\", \"workerGroup\" fill(previous)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "running" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}