{
 "title": "Android HW - Cluster Status",
 "tags": [
  "android",
  "android_main_alerts"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Device Health Percentage",
   "type": "graph",
   "description": "working (non-problem) workers / configured workers",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "percent" }
   ],
   "targets": [
    {
     "alias": "functioning worker %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "bitbar_workers",
     "query": "SELECT ((sum(\"configured\")- sum(\"problem\")) / sum(\"configured\")) * 100  FROM \"bitbar_workers\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "configured" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Device Health",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ((sum(\"configured\")- sum(\"problem\")) / sum(\"configured\")) * 100  FROM \"bitbar_workers\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "active vs configured workers",
   "type": "graph",
   "description": "all queues need to have work in order to reach full utilization (rarely the case). see link below.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "active workers (non-test)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_web_exec",
     "query": "SELECT sum(\"max\") FROM ( SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"provisionerId\" = 'proj-autophone' AND \"workerType\" !~ /test/) GROUP BY \"workerType\" fill(null) ) WHERE $timeFilter  GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "proj-autophone" },
      { "condition": "AND", "key": "workerType", "operator": "=", "value": "gecko-t-bitbar-gw-batt-g5" }
     ]
    },
    {
     "alias": "queued jobs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"bitbar_queue_size\" WHERE (\"queue\" !~ /test/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "configured workers (non-test)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bitbar_workers",
     "query": "SELECT sum(\"configured\") FROM \"bitbar_workers\" WHERE $timeFilter AND \"queue\" !~ /test/ GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "configured" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "configured proj-autophone workers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "$tag_queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "workers",
     "query": "SELECT max(\"configured\") FROM \"bitbar_workers\" WHERE (\"provisioner\" = 'proj-autophone') AND $timeFilter GROUP BY time($__interval), \"queue\" fill(none)\n",
     "select": [
      [
       { "params": [ "missing" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "configured total",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "workers",
     "query": "SELECT sum(\"configured\") FROM \"bitbar_workers\" WHERE (\"provisioner\" = 'proj-autophone') AND $timeFilter GROUP BY time(1m) fill(none)",
     "select": [
      [
       { "params": [ "configured" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "problem proj-autophone workers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "$tag_queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "bitbar_workers",
     "query": "SELECT sum(\"missing\") FROM \"workers\" WHERE $timeFilter GROUP BY time($__interval), \"queue\" fill(none)",
     "select": [
      [
       { "params": [ "problem" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "provisioner", "operator": "=", "value": "proj-autophone" },
      { "condition": "AND", "key": "queue", "operator": "!=", "value": "pixel2-unit-2" }
     ]
    },
    {
     "alias": "problem total",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "bitbar_workers",
     "query": "SELECT sum(\"missing\") FROM \"workers\" WHERE $timeFilter GROUP BY time(1m) fill(none)\n",
     "select": [
      [
       { "params": [ "problem" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "provisioner", "operator": "=", "value": "proj-autophone" }
     ]
    }
   ]
  }
 ]
}