{
 "title": "Android Queues",
 "tags": [
  "android",
  "android_main_alerts"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Android Hardware (Bitbar)",
   "type": "graph",
   "description": "proj-autophone/gecko-t-ap-*",
   "gridPos": { "h": 14, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "jobs" }
   ],
   "targets": [
    {
     "alias": "proj-autophone/$tag_queue jobs",
     "groupBy": [
      { "params": [ "queue" ], "type": "tag" }
     ],
     "measurement": "current",
     "query": "SELECT * FROM \"bitbar_queue_size\" WHERE (\"queue\" !~ /test/) AND $timeFilter GROUP BY \"queue\";\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "queue", "operator": "=", "value": "gecko-t-ap-batt-g5" }
     ]
    },
    {
     "alias": "android_hw_total jobs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"bitbar_queue_size\" WHERE (\"queue\" !~ /test/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Android Hw Bitbar Jobs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bitbar_queue_size",
     "query": "SELECT sum(\"value\") FROM \"bitbar_queue_size\" WHERE queue !~ /test/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Android Hw Health",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ((sum(\"configured\")- sum(\"problem\")) / sum(\"configured\")) * 100  FROM \"bitbar_workers\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Android Emulated",
   "type": "graph",
   "description": "aws queue shows non-android work",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "jobs" }
   ],
   "targets": [
    {
     "alias": "gecko-t/t-linux-kvm-gcp jobs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "gecko-t" },
      { "condition": "AND", "key": "workerType", "operator": "=", "value": "t-linux-kvm-noscratch-gcp" }
     ]
    },
    {
     "alias": "gecko-t/t-linux-kvm-gcp running workers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "gecko-t" },
      { "condition": "AND", "key": "workerType", "operator": "=", "value": "t-linux-kvm-noscratch-gcp" }
     ]
    }
   ]
  },
  {
   "title": "Android-Em Queue Jobs",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "tc_queue_exec",
     "query": "SELECT sum(\"pendingTasks\") FROM \"six_month\".\"tc_queue_exec\" WHERE (\"provisionerId\" = 'gecko-t' AND \"workerType\" = 't-linux-kvm-noscratch-gcp') AND $timeFilter GROUP BY time(1m) fill(null)\n\n",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "gecko-t" },
      { "condition": "AND", "key": "workerType", "operator": "=", "value": "t-linux-kvm-gcp" }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Lag Alerts",
   "type": "alertlist",
   "gridPos": { "h": 16, "w": 6, "x": 7, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Android Hw Workers",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "queue" ], "type": "tag" }
     ],
     "measurement": "bitbar_workers",
     "query": "SELECT \"configured\", \"problem\" FROM \"bitbar_workers\" WHERE $timeFilter GROUP BY \"queue\" ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "configured" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Android Em Workers",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 32 },
   "targets": [
    {
     "measurement": "tc_queue2_exec",
     "query": "SELECT \"provisionerId\"::tag, \"workerType\"::tag ,  \"workers\", \"quarantinedWorkers\" FROM \"tc_web_exec\" WHERE (\"provisionerId\" = 'gecko-t') AND $timeFilter  ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "recently running workers" ], "type": "alias" }
      ],
      [
       { "params": [ "quarantined" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "quarantined" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "gecko-t" },
      { "condition": "AND", "key": "workerType", "operator": "=", "value": "t-linux-kvm-noscratch-gcp" }
     ]
    }
   ]
  }
 ]
}