{
 "title": "Android HW - Devicepool Details",
 "description": "InfluxDB dashboards for telegraf metrics",
 "tags": [
  "android",
  "devicepool"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   { "name": "inter", "label": "Interval", "query": "10s,30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Quick overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT non_negative_derivative(mean(\"usage_iowait\"), 1s) FROM \"cpu\" WHERE \"host\" =~ /^$server$/ AND \"cpu\" = 'cpu-total' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "RootFS used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "SELECT mean(usage_user) as \"user\", mean(usage_system) as \"system\", mean(usage_softirq) as \"softirq\", mean(usage_steal) as \"steal\", mean(usage_nice) as \"nice\", mean(usage_irq) as \"irq\", mean(usage_iowait) as \"iowait\", mean(usage_guest) as \"guest\", mean(usage_guest_nice) as \"guest_nice\"  FROM \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load averages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "system_load1",
     "query": "SELECT mean(load1) as short,mean(load5) as medium,mean(load15) as long FROM \"system\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mem_inactive",
     "query": "SELECT mean(total) as total, mean(used) as used, mean(cached) as cached, mean(free) as free, mean(buffered) as buffered  FROM \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Swap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Swap I/O bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "swap_in",
     "query": "SELECT mean(\"in\") as \"in\", mean(\"out\") as \"out\" FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Swap usage (percent)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "swap_in",
     "query": "SELECT mean(used_percent) as used FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Swap usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "swap_in",
     "query": "SELECT mean(free) as \"free\", mean(used) as \"used\", mean(total) as \"total\" FROM \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_path : $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "SELECT mean(total) AS \"total\", mean(used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" = '/' AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk inodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_path : $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "disk_inodes_free",
     "query": "SELECT mean(inodes_free) as \"free\", mean(inodes_used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" = '/' AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}