{
 "title": "cshields Workers Copy",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "provisioner",
    "query": "SHOW TAG VALUES FROM six_month./tc_queue/ WITH KEY = \"provisionerId\" "
   },
   {
    "name": "workerType",
    "query": "SHOW TAG VALUES FROM six_month./tc_queue/ WITH KEY = \"workerType\" WHERE provisionerId =~ /$provisioner/ "
   },
   { "name": "Adhoc" }
  ]
 },
 "panels": [
  {
   "title": "Last Task Status",
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "tasks" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"completed\") AS \"completed\" FROM \"one_week\"./tc_queue/,\"six_month\"./tc_queue/ WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval * 10), \"workerType\", \"provisionerId\" fill(none)",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "failed" ], "type": "alias" }
      ],
      [
       { "params": [ "exception" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "exception" ], "type": "alias" }
      ],
      [
       { "params": [ "completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "completed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  },
  {
   "title": "TC Worker Backlog/Workers",
   "type": "graph",
   "description": "= Queued tasks / workers running tasks\nfiltered to:\nreleng-hardware\naws-provisioner-v1 with /^(mobile|app-services|gecko)-/\nterraform-packet",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "task overload" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $tag_provisionerId $col",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"pendingTasks\") / (mean(\"running\")) as \"runner load\" FROM six_month./tc_queue2/ WHERE $timeFilter AND \"workerType\" != '' AND \"provisionerId\" != 'aws-provisioner-v1' AND \"provisionerId\" != 'gce' AND (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) AND \"workerType\" !~ /-(beta|staging|macstadium)$/ GROUP BY time(15m), \"workerType\", \"provisionerId\" fill(1)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/.*win7.*gpu/" }
     ]
    },
    {
     "alias": "$tag_workerType $tag_provisionerId $col",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"pendingTasks\") / (mean(\"running\")) as \"runner load\" FROM six_month.\"tc_queue2_exec\" WHERE $timeFilter AND \"workerType\" != '' AND (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) AND \"provisionerId\" = 'aws-provisioner-v1' AND \"workerType\" =~ /^(mobile|app-services|gecko)-.*/ GROUP BY time(20m), \"workerType\", \"provisionerId\" fill(1)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/.*win7.*gpu/" }
     ]
    },
    {
     "alias": "$tag_workerType $tag_provisionerId $col alert",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"pendingTasks\") / (mean(\"running\")) as \"runner load\" FROM six_month.\"tc_queue2_exec\" WHERE $timeFilter AND \"provisionerId\" != 'aws-provisioner-v1' AND \"provisionerId\" != 'gce' AND \"workerType\" != '' AND \"workerType\" !~ /-(beta|staging|macstadium)$/ GROUP BY time(20m), \"workerType\", \"provisionerId\" fill(1)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/.*win7.*gpu/" }
     ]
    },
    {
     "alias": "$tag_workerType $tag_provisionerId $col alert",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"pendingTasks\") / (mean(\"running\")) as \"runner load\" FROM six_month.\"tc_queue_exec\" WHERE $timeFilter AND \"provisionerId\" = 'terraform-packet' AND \"workerType\" != '' GROUP BY time(20m), \"workerType\", \"provisionerId\" fill(1)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/.*win7.*gpu/" }
     ]
    },
    {
     "alias": "$tag_workerType $tag_provisionerId $col alert",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"pendingTasks\") / (mean(\"running\")) as \"runner load\" FROM six_month.\"tc_queue2_exec\" WHERE $timeFilter AND \"provisionerId\" = 'aws-provisioner-v1' AND \"workerType\" =~ /^gecko-.*/ GROUP BY time(20m), \"workerType\", \"provisionerId\" fill(1)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/.*win7.*gpu/" }
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "graph",
   "description": "<https://wiki.mozilla.org/CIDuty/How_To/High_Pending_Counts>",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "queued tasks" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $tag_provisionerId $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT mean(\"pendingTasks\") AS \"queue\" FROM /^tc_queue/ WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval), \"workerType\", \"provisionerId\" fill(none)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "$tag_workerType $tag_provisionerId $col alert",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT mean(\"pendingTasks\") AS \"queue\" FROM /^tc_queue_exec/ WHERE $timeFilter GROUP BY time($__interval), \"workerType\", \"provisionerId\" fill(none)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Task Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "tasks" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"failed\") AS \"failed\", mean(\"exception\") AS \"exception\", mean(\"completed\") AS \"completed\" FROM \"one_week\"./tc_queue/,\"six_month\"./tc_queue/ WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval * 10), \"workerType\", \"provisionerId\" fill(none)",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "failed" ], "type": "alias" }
      ],
      [
       { "params": [ "exception" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "exception" ], "type": "alias" }
      ],
      [
       { "params": [ "completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "completed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  }
 ]
}