{
 "title": "DC Usage",
 "time": { "from": "now-70d", "to": "now+7d" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "provisioner",
    "query": "SHOW TAG VALUES FROM /tc_queue/ WITH KEY = \"provisionerId\" "
   },
   {
    "name": "workerType",
    "query": "SHOW TAG VALUES FROM /tc_queue/ WITH KEY = \"workerType\" WHERE provisionerId =~ /$provisioner/ "
   }
  ]
 },
 "panels": [
  {
   "title": "Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "running",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT sum(\"mean\") FROM (SELECT mean(\"running\") FROM \"six_month\".\"tc_queue2_exec\" WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY \"provisionerId\", \"workerType\", time($interval) fill(none)) GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "queued",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT sum(\"max\") FROM (SELECT max(\"pendingTasks\") FROM \"tc_queue_exec\" WHERE \"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/ AND $timeFilter GROUP BY \"provisionerId\", \"workerType\", time($interval) fill(null)) GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "releng-hardware" }
     ]
    }
   ]
  },
  {
   "title": "Usage % (TC API)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "hourly $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"running\") / sum(\"workers\") as \"max\", sum(\"rmean\") / sum(\"wmean\") as \"mean\" FROM (SELECT max(\"workers\") as \"workers\", max(\"running\") as \"running\", mean(\"workers\") as \"wmean\", mean(\"running\") as \"rmean\" FROM \"tc_queue2_exec\" WHERE \"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/ AND $timeFilter GROUP BY \"provisionerId\", \"workerType\", time($interval)) GROUP BY time($interval * 2) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "daily $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"running\") / sum(\"workers\") as \"max\", sum(\"rmean\") / sum(\"wmean\") as \"mean\" FROM (SELECT max(\"workers\") as \"workers\", max(\"running\") as \"running\", mean(\"workers\") as \"wmean\", mean(\"running\") as \"rmean\" FROM \"tc_queue2_exec\" WHERE \"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/ AND $timeFilter GROUP BY \"provisionerId\", \"workerType\", time($interval)) GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Usage % (TC API)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "daily $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"running\") / sum(\"workers\") as \"max\" FROM (SELECT max(\"workers\") as \"workers\", max(\"running\") as \"running\" FROM \"tc_queue2_exec\" WHERE \"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/ AND $timeFilter GROUP BY \"provisionerId\", \"workerType\", time($interval)) GROUP BY time(6h) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "forecast",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT HOLT_WINTERS_WITH_FIT(first(\"max\"),28,28) FROM (SELECT sum(\"running\") / sum(\"workers\") as \"max\" FROM (SELECT max(\"workers\") as \"workers\", max(\"running\") as \"running\" FROM \"tc_queue2_exec\" WHERE \"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/ AND $timeFilter GROUP BY \"provisionerId\", \"workerType\", time($interval)) GROUP BY time($__interval) fill(none)) GROUP BY time(6h) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Time research", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Usage (logged)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "20m $col",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT count(\"count\") FROM (SELECT count(\"count\") FROM \"papertrail\" WHERE \"event\" = 'task' AND $timeFilter GROUP BY \"host\", time(20m) fill(none)) GROUP BY time(20m) fill(previous)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/^no task/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
     ]
    },
    {
     "alias": "30m $col",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT count(\"count\") FROM (SELECT count(\"count\") FROM \"papertrail\" WHERE \"event\" = 'task' AND $timeFilter GROUP BY \"host\", time(30m) fill(none)) GROUP BY time(30m) fill(linear)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/^no task/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT count(\"count\") FROM (SELECT count(\"count\") FROM \"papertrail\" WHERE \"event\" = 'task' AND $timeFilter GROUP BY \"host\", time(12h) fill(none)) GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/^no task/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
     ]
    }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "task logged",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_event",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT count(\"count\") FROM \"papertrail\" WHERE \"event\" = 'no task' OR \"event\" = 'task' AND $timeFilter GROUP BY \"event\", time(10m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/^no task/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^tc_queue/",
     "query": "SELECT mean(\"running\") as \"tc count\", mean(\"pendingTasks\") as \"queue\" FROM /^tc_queue/ WHERE (\"provisionerId\" = 'releng-hardware') AND $timeFilter GROUP BY time(5m) fill(previous)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "releng-hardware" }
     ]
    }
   ]
  },
  {
   "title": "worker process",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "generic-worker" }
     ]
    }
   ]
  },
  {
   "title": "Usage (logged)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "10m $col $tag_event",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT max(\"count\"), mean(\"count\"), ((max(\"count\") + mean(\"count\"))/2)as \"level\" FROM (SELECT count(\"count\") FROM \"papertrail\" WHERE (\"event\" = 'no task' OR \"event\" = 'task') AND $timeFilter GROUP BY \"event\", time(1m) fill(none)) GROUP BY \"event\", time(10m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/^no task/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
     ]
    },
    {
     "alias": "daily $col $tag_event",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT mean(\"mean\"), max(\"max\") FROM (SELECT max(\"count\"), mean(\"count\") FROM (SELECT count(\"count\") FROM \"papertrail\" WHERE (\"event\" = 'no task' OR \"event\" = 'task') AND $timeFilter GROUP BY \"event\", time(1m) fill(none)) GROUP BY \"event\", time(10m)) GROUP BY \"event\", time(3h)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/^no task/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage AVG",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "generic-worker" }
     ]
    }
   ]
  },
  {
   "title": "worker logging",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "datacenter",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/worker activity/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
     ]
    },
    {
     "alias": "cloud",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/worker activity/" },
      { "condition": "AND", "key": "host", "operator": "!~", "value": "/mdc[0-9].mozilla.com$/" }
     ]
    },
    {
     "alias": "datacenter all",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "space" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
     ]
    },
    {
     "alias": "cloud all",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "space" },
      { "condition": "AND", "key": "host", "operator": "!~", "value": "/mdc[0-9].mozilla.com$/" }
     ]
    }
   ]
  },
  {
   "title": "Active count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "not releng-hardware daily total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM (SELECT mean(\"running\") as \"value\" FROM \"tc_queue2_exec\" WHERE \"provisionerId\" != 'releng-hardware' AND $timeFilter GROUP BY time(1d), \"provisionerId\", \"workerType\" fill(null)) GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "releng_hardware",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM (SELECT mean(\"running\") as \"value\" FROM \"tc_queue2_exec\" WHERE \"provisionerId\" = 'releng-hardware' AND $timeFilter GROUP BY time(1d), \"provisionerId\", \"workerType\" fill(null)) GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "hw tasks started",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "event" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT sum(\"count\") AS \"count\" FROM \"papertrail\" WHERE \"event\" =~ /task start/ AND \"host\" =~ /\\.mdc[12]\\./ AND \"host\" =~ /${hostname}/ AND $timeFilter GROUP BY time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/task start/" }
     ]
    },
    {
     "alias": "cloud tasks started",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "event" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT sum(\"count\") AS \"count\" FROM \"papertrail\" WHERE \"event\" =~ /task start/ AND \"host\" !~ /\\.mdc[12]\\./ AND \"host\" =~ /${hostname}/ AND $timeFilter GROUP BY time(1d) fill(linear)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/task start/" }
     ]
    }
   ]
  },
  {
   "title": "DC Instances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "hardware workers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM (SELECT mean(\"workers\") as \"value\" FROM \"tc_queue_exec\" WHERE (\"provisionerId\" = 'releng-hardware') AND \"workerType\" !~ /gamma$/ AND $timeFilter GROUP BY time(1d), \"provisionerId\", \"workerType\" fill(null)) GROUP BY time(1d) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cloud Instances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_provisionerId $tag_workerType daily total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM (SELECT mean(\"workers\") as \"value\" FROM \"tc_queue_exec\" WHERE (\"provisionerId\" != 'releng-hardware') AND \"workerType\" !~ /gamma$/ AND $timeFilter GROUP BY time(1d), \"provisionerId\", \"workerType\" fill(null)) GROUP BY time(1d), \"provisionerId\", \"workerType\" fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}