{
 "title": "GCP/AWS Builder Counts",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "fxci-level1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aliasBy": "fxci-level1",
     "alignOptions": [
      {
       "expanded": true,
       "label": "Alignment options",
       "options": [
        {
         "label": "interpolate",
         "metricKinds": [ "GAUGE" ],
         "text": "interpolate",
         "value": "ALIGN_INTERPOLATE",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "next older",
         "metricKinds": [ "GAUGE" ],
         "text": "next older",
         "value": "ALIGN_NEXT_OLDER",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "DISTRIBUTION",
          "STRING",
          "VALUE_TYPE_UNSPECIFIED",
          "BOOL"
         ]
        },
        {
         "label": "min",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "min",
         "value": "ALIGN_MIN",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "max",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "max",
         "value": "ALIGN_MAX",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "mean",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "mean",
         "value": "ALIGN_MEAN",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "count",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "count",
         "value": "ALIGN_COUNT",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "BOOL"
         ]
        },
        {
         "label": "sum",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "sum",
         "value": "ALIGN_SUM",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "DISTRIBUTION"
         ]
        },
        {
         "label": "stddev",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "stddev",
         "value": "ALIGN_STDDEV",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "percent change",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "percent change",
         "value": "ALIGN_PERCENT_CHANGE",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        }
       ]
      }
     ],
     "alignmentPeriod": "stackdriver-auto",
     "crossSeriesReducer": "REDUCE_COUNT",
     "defaultProject": "loading project...",
     "filters": [
      "resource.label.project_id",
      "=",
      "fxci-production-level1-workers"
     ],
     "groupBys": [ "resource.label.project_id" ],
     "lastQuery": "aggregation.alignmentPeriod=+3600s&aggregation.crossSeriesReducer=REDUCE_COUNT&aggregation.groupByFields=resource.label.project_id&aggregation.perSeriesAligner=ALIGN_INTERPOLATE&filter=metric.type=\"compute.googleapis.com/instance/cpu/utilization\"+resource.label.project_id=\"fxci-production-level1-workers\"&interval.endTime=2020-04-04T23:59:59Z&interval.startTime=2020-03-29T00:00:00Z&view=FULL",
     "metricKind": "GAUGE",
     "metricType": "compute.googleapis.com/instance/cpu/utilization",
     "perSeriesAligner": "ALIGN_INTERPOLATE",
     "unit": "10^2.%",
     "usedAlignmentPeriod": 3600,
     "valueType": "DOUBLE"
    }
   ]
  },
  {
   "title": "fxci-level3",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aliasBy": "fxci-level3",
     "alignOptions": [
      {
       "expanded": true,
       "label": "Alignment options",
       "options": [
        {
         "label": "interpolate",
         "metricKinds": [ "GAUGE" ],
         "text": "interpolate",
         "value": "ALIGN_INTERPOLATE",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "next older",
         "metricKinds": [ "GAUGE" ],
         "text": "next older",
         "value": "ALIGN_NEXT_OLDER",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "DISTRIBUTION",
          "STRING",
          "VALUE_TYPE_UNSPECIFIED",
          "BOOL"
         ]
        },
        {
         "label": "min",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "min",
         "value": "ALIGN_MIN",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "max",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "max",
         "value": "ALIGN_MAX",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "mean",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "mean",
         "value": "ALIGN_MEAN",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "count",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "count",
         "value": "ALIGN_COUNT",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "BOOL"
         ]
        },
        {
         "label": "sum",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "sum",
         "value": "ALIGN_SUM",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "DISTRIBUTION"
         ]
        },
        {
         "label": "stddev",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "stddev",
         "value": "ALIGN_STDDEV",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "percent change",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "percent change",
         "value": "ALIGN_PERCENT_CHANGE",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        }
       ]
      }
     ],
     "alignmentPeriod": "stackdriver-auto",
     "crossSeriesReducer": "REDUCE_COUNT",
     "defaultProject": "loading project...",
     "filters": [
      "resource.label.project_id",
      "=",
      "fxci-production-level3-workers"
     ],
     "groupBys": [ "resource.label.project_id" ],
     "lastQuery": "aggregation.alignmentPeriod=+3600s&aggregation.crossSeriesReducer=REDUCE_COUNT&aggregation.groupByFields=resource.label.project_id&aggregation.perSeriesAligner=ALIGN_INTERPOLATE&filter=metric.type=\"compute.googleapis.com/instance/cpu/utilization\"+resource.label.project_id=\"fxci-production-level1-workers\"&interval.endTime=2020-04-04T23:59:59Z&interval.startTime=2020-03-29T00:00:00Z&view=FULL",
     "metricKind": "GAUGE",
     "metricType": "compute.googleapis.com/instance/cpu/utilization",
     "perSeriesAligner": "ALIGN_INTERPOLATE",
     "unit": "10^2.%",
     "usedAlignmentPeriod": 3600,
     "valueType": "DOUBLE"
    }
   ]
  },
  {
   "title": "task errors",
   "type": "graph",
   "description": "Errors across all task types (not limited to builders).",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "aws",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "task error" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^i-/" }
     ]
    },
    {
     "alias": "datacenter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "task error" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc/" }
     ]
    },
    {
     "alias": "gcp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "task error" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/-gcp-/" }
     ]
    }
   ]
  },
  {
   "title": "task timeouts",
   "type": "graph",
   "description": "Timeouts across all task types. Not limited to builders. Timeout lags by avg 5400s (90m).",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval * 2" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "hgtimeout" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^fxci/" }
     ]
    },
    {
     "alias": "non-gcp task timeout count",
     "groupBy": [
      { "params": [ "$__interval * 2" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "hgtimeout" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^nongcp/" }
     ]
    },
    {
     "alias": "task timeout $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/^Task timeout/" }
     ]
    }
   ]
  },
  {
   "title": "task start/end",
   "type": "graph",
   "description": "All task types (not limited to builders).",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "aws $tag_event",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "event" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/^task (start|end|success)/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^i-/" }
     ]
    },
    {
     "alias": "datacenter $tag_event",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "event" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/^task (start|end|success)/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc/" }
     ]
    },
    {
     "alias": "gcp $tag_event",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "event" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/^task (start|end|success)/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/-gcp-/" }
     ]
    }
   ]
  },
  {
   "title": "90 Days Top",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Peak instance count. With date of peak. Grouped aws as \"non-gcp total\": top(sum(max(count) by workerType not \"-gcp\"))",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "alias": "$tag_workerType",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT top(max, workerType,15) FROM (SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /^b-linux-gcp/) AND $timeFilter  GROUP BY time(1w),  \"workerType\" fill(null))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_workerType",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT top(max, workerType,15) FROM (SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /^b-linux/ AND \"workerType\" !~ /^b-linux-gcp/) AND $timeFilter  GROUP BY time(1w), \"workerType\"  fill(null))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "non-gcp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT top(sum,3), sum AS \"workerType\" FROM (SELECT sum(\"max\") FROM (SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /^b-linu(x|x-aws)/ AND \"workerType\" !~ /b-linux-gcp/) AND $timeFilter GROUP BY \"workerType\", time($interval*2)  fill(linear)) GROUP BY time($interval*2) fill(linear))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "AWS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "AWS EC2",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{Action}}",
     "dimensions": { "Action": "RunInstances" },
     "metricName": "SuccessfulCalls",
     "namespace": "AWS/EC2/API",
     "period": "10m",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "{{Action}} {{label}}",
     "dimensions": { "Action": "RunInstances" },
     "metricName": "ClientErrors",
     "namespace": "AWS/EC2/API",
     "period": "10m",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "{{Action}} {{label}}",
     "dimensions": { "Action": "RunInstances" },
     "metricName": "ServerErrors",
     "namespace": "AWS/EC2/API",
     "period": "10m",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "AWS EC2",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{Action}}",
     "dimensions": { "Action": "TerminateInstances" },
     "metricName": "SuccessfulCalls",
     "namespace": "AWS/EC2/API",
     "period": "10m",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "{{Action}} {{label}}",
     "dimensions": { "Action": "TerminateInstances" },
     "metricName": "ClientErrors",
     "namespace": "AWS/EC2/API",
     "period": "10m",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "{{Action}} {{label}}",
     "dimensions": { "Action": "TerminateInstances" },
     "metricName": "ServerErrors",
     "namespace": "AWS/EC2/API",
     "period": "10m",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "GCP Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "GCP",
     "type": "graph",
     "description": "https://console.cloud.google.com/monitoring/metrics-explorer?organizationId=442341870013&project=fxci-production-logging&supportedpurview=project&pageState=%7B%22xyChart%22:%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22compute.googleapis.com%2Finstance%2Fcpu%2Freserved_cores%5C%22%20resource.type%3D%5C%22gce_instance%5C%22%22,%22minAlignmentPeriod%22:%2260s%22,%22unitOverride%22:%221%22,%22aggregations%22:%5B%7B%22perSeriesAligner%22:%22ALIGN_MEAN%22,%22crossSeriesReducer%22:%22REDUCE_SUM%22,%22groupByFields%22:%5B%22resource.label.%5C%22project_id%5C%22%22%5D%7D,%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22%7D%5D%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLines%22:%5B%5D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D,%22isAutoRefresh%22:true,%22timeSelection%22:%7B%22timeRange%22:%221w%22%7D%7D",
     "gridPos": { "h": 4, "w": 20, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aliasBy": "{{resource.label.project_id}}",
       "alignOptions": [
        {
         "expanded": true,
         "label": "Alignment options",
         "options": [
          {
           "label": "interpolate",
           "metricKinds": [ "GAUGE" ],
           "text": "interpolate",
           "value": "ALIGN_INTERPOLATE",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "next older",
           "metricKinds": [ "GAUGE" ],
           "text": "next older",
           "value": "ALIGN_NEXT_OLDER",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "DISTRIBUTION",
            "STRING",
            "VALUE_TYPE_UNSPECIFIED",
            "BOOL"
           ]
          },
          {
           "label": "min",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "min",
           "value": "ALIGN_MIN",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "max",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "max",
           "value": "ALIGN_MAX",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "mean",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "mean",
           "value": "ALIGN_MEAN",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "count",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "count",
           "value": "ALIGN_COUNT",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "BOOL"
           ]
          },
          {
           "label": "sum",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "sum",
           "value": "ALIGN_SUM",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "DISTRIBUTION"
           ]
          },
          {
           "label": "stddev",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "stddev",
           "value": "ALIGN_STDDEV",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "percent change",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "percent change",
           "value": "ALIGN_PERCENT_CHANGE",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          }
         ]
        }
       ],
       "alignmentPeriod": "stackdriver-auto",
       "crossSeriesReducer": "REDUCE_COUNT",
       "defaultProject": "loading project...",
       "groupBys": [ "resource.label.project_id" ],
       "lastQuery": "aggregation.alignmentPeriod=+3600s&aggregation.crossSeriesReducer=REDUCE_STDDEV&aggregation.groupByFields=resource.label.project_id&aggregation.perSeriesAligner=ALIGN_INTERPOLATE&filter=metric.type=\"compute.googleapis.com/instance/cpu/utilization\"&interval.endTime=2020-04-01T17:29:54Z&interval.startTime=2020-03-25T17:29:54Z&view=FULL",
       "metricKind": "GAUGE",
       "metricType": "compute.googleapis.com/instance/cpu/utilization",
       "perSeriesAligner": "ALIGN_INTERPOLATE",
       "unit": "10^2.%",
       "usedAlignmentPeriod": 3600,
       "valueType": "DOUBLE"
      }
     ]
    },
    {
     "type": "graph",
     "description": "https://console.cloud.google.com/monitoring/metrics-explorer?organizationId=442341870013&project=fxci-production-logging&supportedpurview=project&pageState=%7B%22xyChart%22:%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22compute.googleapis.com%2Finstance%2Fcpu%2Freserved_cores%5C%22%20resource.type%3D%5C%22gce_instance%5C%22%22,%22minAlignmentPeriod%22:%2260s%22,%22unitOverride%22:%221%22,%22aggregations%22:%5B%7B%22perSeriesAligner%22:%22ALIGN_MEAN%22,%22crossSeriesReducer%22:%22REDUCE_SUM%22,%22groupByFields%22:%5B%22resource.label.%5C%22project_id%5C%22%22%5D%7D,%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22%7D%5D%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLines%22:%5B%5D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D,%22isAutoRefresh%22:true,%22timeSelection%22:%7B%22timeRange%22:%221w%22%7D%7D",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aliasBy": "vCPUs {{resource.label.project_id}}",
       "alignOptions": [
        {
         "expanded": true,
         "label": "Alignment options",
         "options": [
          {
           "label": "interpolate",
           "metricKinds": [ "GAUGE" ],
           "text": "interpolate",
           "value": "ALIGN_INTERPOLATE",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "next older",
           "metricKinds": [ "GAUGE" ],
           "text": "next older",
           "value": "ALIGN_NEXT_OLDER",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "DISTRIBUTION",
            "STRING",
            "VALUE_TYPE_UNSPECIFIED",
            "BOOL"
           ]
          },
          {
           "label": "min",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "min",
           "value": "ALIGN_MIN",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "max",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "max",
           "value": "ALIGN_MAX",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "mean",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "mean",
           "value": "ALIGN_MEAN",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "count",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "count",
           "value": "ALIGN_COUNT",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "BOOL"
           ]
          },
          {
           "label": "sum",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "sum",
           "value": "ALIGN_SUM",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "DISTRIBUTION"
           ]
          },
          {
           "label": "stddev",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "stddev",
           "value": "ALIGN_STDDEV",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "percent change",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "percent change",
           "value": "ALIGN_PERCENT_CHANGE",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          }
         ]
        }
       ],
       "alignmentPeriod": "stackdriver-auto",
       "crossSeriesReducer": "REDUCE_SUM",
       "defaultProject": "loading project...",
       "groupBys": [ "resource.label.project_id" ],
       "lastQuery": "aggregation.alignmentPeriod=+3600s&aggregation.crossSeriesReducer=REDUCE_SUM&aggregation.groupByFields=resource.label.project_id&aggregation.perSeriesAligner=ALIGN_INTERPOLATE&filter=metric.type=\"compute.googleapis.com/instance/cpu/reserved_cores\"&interval.endTime=2020-04-01T17:36:46Z&interval.startTime=2020-03-25T17:36:46Z&view=FULL",
       "metricKind": "GAUGE",
       "metricType": "compute.googleapis.com/instance/cpu/reserved_cores",
       "perSeriesAligner": "ALIGN_INTERPOLATE",
       "unit": "1",
       "usedAlignmentPeriod": 3600,
       "valueType": "DOUBLE"
      }
     ]
    },
    {
     "type": "graph",
     "description": "https://console.cloud.google.com/monitoring/metrics-explorer?organizationId=442341870013&project=fxci-production-logging&supportedpurview=project&pageState=%7B%22xyChart%22:%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22compute.googleapis.com%2Finstance%2Fcpu%2Freserved_cores%5C%22%20resource.type%3D%5C%22gce_instance%5C%22%22,%22minAlignmentPeriod%22:%2260s%22,%22unitOverride%22:%221%22,%22aggregations%22:%5B%7B%22perSeriesAligner%22:%22ALIGN_MEAN%22,%22crossSeriesReducer%22:%22REDUCE_SUM%22,%22groupByFields%22:%5B%22resource.label.%5C%22project_id%5C%22%22%5D%7D,%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22%7D%5D%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLines%22:%5B%5D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D,%22isAutoRefresh%22:true,%22timeSelection%22:%7B%22timeRange%22:%221w%22%7D%7D",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "aliasBy": "max util {{resource.label.project_id}}",
       "alignOptions": [
        {
         "expanded": true,
         "label": "Alignment options",
         "options": [
          {
           "label": "interpolate",
           "metricKinds": [ "GAUGE" ],
           "text": "interpolate",
           "value": "ALIGN_INTERPOLATE",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "next older",
           "metricKinds": [ "GAUGE" ],
           "text": "next older",
           "value": "ALIGN_NEXT_OLDER",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "DISTRIBUTION",
            "STRING",
            "VALUE_TYPE_UNSPECIFIED",
            "BOOL"
           ]
          },
          {
           "label": "min",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "min",
           "value": "ALIGN_MIN",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "max",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "max",
           "value": "ALIGN_MAX",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "mean",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "mean",
           "value": "ALIGN_MEAN",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "count",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "count",
           "value": "ALIGN_COUNT",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "BOOL"
           ]
          },
          {
           "label": "sum",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "sum",
           "value": "ALIGN_SUM",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "DISTRIBUTION"
           ]
          },
          {
           "label": "stddev",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "stddev",
           "value": "ALIGN_STDDEV",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "percent change",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "percent change",
           "value": "ALIGN_PERCENT_CHANGE",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          }
         ]
        }
       ],
       "alignmentPeriod": "stackdriver-auto",
       "crossSeriesReducer": "REDUCE_PERCENTILE_99",
       "defaultProject": "loading project...",
       "groupBys": [ "resource.label.project_id" ],
       "lastQuery": "aggregation.alignmentPeriod=+3600s&aggregation.crossSeriesReducer=REDUCE_PERCENTILE_95&aggregation.groupByFields=resource.label.project_id&aggregation.perSeriesAligner=ALIGN_INTERPOLATE&filter=metric.type=\"compute.googleapis.com/instance/cpu/utilization\"&interval.endTime=2020-04-01T17:44:06Z&interval.startTime=2020-03-25T17:44:06Z&view=FULL",
       "metricKind": "GAUGE",
       "metricType": "compute.googleapis.com/instance/cpu/utilization",
       "perSeriesAligner": "ALIGN_INTERPOLATE",
       "unit": "10^2.%",
       "usedAlignmentPeriod": 3600,
       "valueType": "DOUBLE"
      },
      {
       "aliasBy": "min util {{resource.label.project_id}}",
       "alignOptions": [
        {
         "expanded": true,
         "label": "Alignment options",
         "options": [
          {
           "label": "interpolate",
           "metricKinds": [ "GAUGE" ],
           "text": "interpolate",
           "value": "ALIGN_INTERPOLATE",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "next older",
           "metricKinds": [ "GAUGE" ],
           "text": "next older",
           "value": "ALIGN_NEXT_OLDER",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "DISTRIBUTION",
            "STRING",
            "VALUE_TYPE_UNSPECIFIED",
            "BOOL"
           ]
          },
          {
           "label": "min",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "min",
           "value": "ALIGN_MIN",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "max",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "max",
           "value": "ALIGN_MAX",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "mean",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "mean",
           "value": "ALIGN_MEAN",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "count",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "count",
           "value": "ALIGN_COUNT",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "BOOL"
           ]
          },
          {
           "label": "sum",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "sum",
           "value": "ALIGN_SUM",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "DISTRIBUTION"
           ]
          },
          {
           "label": "stddev",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "stddev",
           "value": "ALIGN_STDDEV",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "percent change",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "percent change",
           "value": "ALIGN_PERCENT_CHANGE",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          }
         ]
        }
       ],
       "alignmentPeriod": "stackdriver-auto",
       "crossSeriesReducer": "REDUCE_MIN",
       "defaultProject": "loading project...",
       "groupBys": [ "resource.label.project_id" ],
       "lastQuery": "aggregation.alignmentPeriod=+3600s&aggregation.crossSeriesReducer=REDUCE_PERCENTILE_05&aggregation.groupByFields=resource.label.project_id&aggregation.perSeriesAligner=ALIGN_INTERPOLATE&filter=metric.type=\"compute.googleapis.com/instance/cpu/utilization\"&interval.endTime=2020-04-01T17:44:02Z&interval.startTime=2020-03-25T17:44:02Z&view=FULL",
       "metricKind": "GAUGE",
       "metricType": "compute.googleapis.com/instance/cpu/utilization",
       "perSeriesAligner": "ALIGN_INTERPOLATE",
       "unit": "10^2.%",
       "usedAlignmentPeriod": 3600,
       "valueType": "DOUBLE"
      }
     ]
    },
    {
     "type": "graph",
     "description": "https://console.cloud.google.com/monitoring/metrics-explorer?organizationId=442341870013&project=fxci-production-logging&supportedpurview=project&pageState=%7B%22xyChart%22:%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22compute.googleapis.com%2Finstance%2Fcpu%2Freserved_cores%5C%22%20resource.type%3D%5C%22gce_instance%5C%22%22,%22minAlignmentPeriod%22:%2260s%22,%22unitOverride%22:%221%22,%22aggregations%22:%5B%7B%22perSeriesAligner%22:%22ALIGN_MEAN%22,%22crossSeriesReducer%22:%22REDUCE_SUM%22,%22groupByFields%22:%5B%22resource.label.%5C%22project_id%5C%22%22%5D%7D,%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22%7D%5D%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLines%22:%5B%5D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D,%22isAutoRefresh%22:true,%22timeSelection%22:%7B%22timeRange%22:%221w%22%7D%7D",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "aliasBy": "cpu usage {{resource.label.project_id}}",
       "alignOptions": [
        {
         "expanded": true,
         "label": "Alignment options",
         "options": [
          {
           "label": "delta",
           "metricKinds": [
            "CUMULATIVE",
            "DELTA"
           ],
           "text": "delta",
           "value": "ALIGN_DELTA",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "DISTRIBUTION"
           ]
          },
          {
           "label": "rate",
           "metricKinds": [
            "CUMULATIVE",
            "DELTA"
           ],
           "text": "rate",
           "value": "ALIGN_RATE",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "min",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "min",
           "value": "ALIGN_MIN",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "max",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "max",
           "value": "ALIGN_MAX",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "mean",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "mean",
           "value": "ALIGN_MEAN",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "count",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "count",
           "value": "ALIGN_COUNT",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "BOOL"
           ]
          },
          {
           "label": "sum",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "sum",
           "value": "ALIGN_SUM",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "DISTRIBUTION"
           ]
          },
          {
           "label": "stddev",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "stddev",
           "value": "ALIGN_STDDEV",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "percent change",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "percent change",
           "value": "ALIGN_PERCENT_CHANGE",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          }
         ]
        }
       ],
       "alignmentPeriod": "stackdriver-auto",
       "crossSeriesReducer": "REDUCE_SUM",
       "defaultProject": "loading project...",
       "groupBys": [ "resource.label.project_id" ],
       "lastQuery": "aggregation.alignmentPeriod=+3600s&aggregation.crossSeriesReducer=REDUCE_SUM&aggregation.groupByFields=resource.label.project_id&aggregation.perSeriesAligner=ALIGN_MAX&filter=metric.type=\"compute.googleapis.com/instance/cpu/usage_time\"&interval.endTime=2020-04-01T17:35:16Z&interval.startTime=2020-03-25T17:35:16Z&view=FULL",
       "metricKind": "DELTA",
       "metricType": "compute.googleapis.com/instance/cpu/usage_time",
       "perSeriesAligner": "ALIGN_DELTA",
       "unit": "s",
       "usedAlignmentPeriod": 3600,
       "valueType": "DOUBLE"
      }
     ]
    },
    {
     "type": "graph",
     "description": "https://console.cloud.google.com/monitoring/metrics-explorer?organizationId=442341870013&project=fxci-production-logging&supportedpurview=project&pageState=%7B%22xyChart%22:%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22compute.googleapis.com%2Finstance%2Fcpu%2Freserved_cores%5C%22%20resource.type%3D%5C%22gce_instance%5C%22%22,%22minAlignmentPeriod%22:%2260s%22,%22unitOverride%22:%221%22,%22aggregations%22:%5B%7B%22perSeriesAligner%22:%22ALIGN_MEAN%22,%22crossSeriesReducer%22:%22REDUCE_SUM%22,%22groupByFields%22:%5B%22resource.label.%5C%22project_id%5C%22%22%5D%7D,%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22%7D%5D%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLines%22:%5B%5D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D,%22isAutoRefresh%22:true,%22timeSelection%22:%7B%22timeRange%22:%221w%22%7D%7D",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "aliasBy": "disk read {{resource.label.project_id}}",
       "alignOptions": [
        {
         "expanded": true,
         "label": "Alignment options",
         "options": [
          {
           "label": "delta",
           "metricKinds": [
            "CUMULATIVE",
            "DELTA"
           ],
           "text": "delta",
           "value": "ALIGN_DELTA",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "DISTRIBUTION"
           ]
          },
          {
           "label": "rate",
           "metricKinds": [
            "CUMULATIVE",
            "DELTA"
           ],
           "text": "rate",
           "value": "ALIGN_RATE",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "min",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "min",
           "value": "ALIGN_MIN",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "max",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "max",
           "value": "ALIGN_MAX",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "mean",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "mean",
           "value": "ALIGN_MEAN",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "count",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "count",
           "value": "ALIGN_COUNT",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "BOOL"
           ]
          },
          {
           "label": "sum",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "sum",
           "value": "ALIGN_SUM",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "DISTRIBUTION"
           ]
          },
          {
           "label": "stddev",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "stddev",
           "value": "ALIGN_STDDEV",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "percent change",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "percent change",
           "value": "ALIGN_PERCENT_CHANGE",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          }
         ]
        }
       ],
       "alignmentPeriod": "stackdriver-auto",
       "crossSeriesReducer": "REDUCE_MEAN",
       "defaultProject": "loading project...",
       "groupBys": [ "resource.label.project_id" ],
       "lastQuery": "aggregation.alignmentPeriod=+3600s&aggregation.crossSeriesReducer=REDUCE_MEAN&aggregation.groupByFields=resource.label.project_id&aggregation.perSeriesAligner=ALIGN_DELTA&filter=metric.type=\"compute.googleapis.com/instance/disk/read_bytes_count\"&interval.endTime=2020-04-01T17:52:04Z&interval.startTime=2020-03-25T17:52:04Z&view=FULL",
       "metricKind": "DELTA",
       "metricType": "compute.googleapis.com/instance/disk/read_bytes_count",
       "perSeriesAligner": "ALIGN_DELTA",
       "unit": "By",
       "usedAlignmentPeriod": 3600,
       "valueType": "INT64"
      },
      {
       "aliasBy": "disk write {{resource.label.project_id}}",
       "alignOptions": [
        {
         "expanded": true,
         "label": "Alignment options",
         "options": [
          {
           "label": "delta",
           "metricKinds": [
            "CUMULATIVE",
            "DELTA"
           ],
           "text": "delta",
           "value": "ALIGN_DELTA",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "DISTRIBUTION"
           ]
          },
          {
           "label": "rate",
           "metricKinds": [
            "CUMULATIVE",
            "DELTA"
           ],
           "text": "rate",
           "value": "ALIGN_RATE",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "min",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "min",
           "value": "ALIGN_MIN",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "max",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "max",
           "value": "ALIGN_MAX",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "mean",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "mean",
           "value": "ALIGN_MEAN",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "count",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "count",
           "value": "ALIGN_COUNT",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "BOOL"
           ]
          },
          {
           "label": "sum",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "sum",
           "value": "ALIGN_SUM",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY",
            "DISTRIBUTION"
           ]
          },
          {
           "label": "stddev",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "stddev",
           "value": "ALIGN_STDDEV",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          },
          {
           "label": "percent change",
           "metricKinds": [
            "GAUGE",
            "DELTA"
           ],
           "text": "percent change",
           "value": "ALIGN_PERCENT_CHANGE",
           "valueTypes": [
            "INT64",
            "DOUBLE",
            "MONEY"
           ]
          }
         ]
        }
       ],
       "alignmentPeriod": "stackdriver-auto",
       "crossSeriesReducer": "REDUCE_MEAN",
       "defaultProject": "loading project...",
       "groupBys": [ "resource.label.project_id" ],
       "lastQuery": "aggregation.alignmentPeriod=+3600s&aggregation.crossSeriesReducer=REDUCE_MEAN&aggregation.groupByFields=resource.label.project_id&aggregation.perSeriesAligner=ALIGN_DELTA&filter=metric.type=\"compute.googleapis.com/instance/disk/write_bytes_count\"&interval.endTime=2020-04-01T17:52:06Z&interval.startTime=2020-03-25T17:52:06Z&view=FULL",
       "metricKind": "DELTA",
       "metricType": "compute.googleapis.com/instance/disk/write_bytes_count",
       "perSeriesAligner": "ALIGN_DELTA",
       "unit": "By",
       "usedAlignmentPeriod": 3600,
       "valueType": "INT64"
      }
     ]
    },
    {
     "title": "queue api - running workers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_provisionerId/$tag_workerType",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "provisionerId" ], "type": "tag" },
        { "params": [ "workerType" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "tc_queue2_exec",
       "region": "default",
       "select": [
        [
         { "params": [ "running" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "statistics": [ "Average" ],
       "tags": [
        { "key": "provisionerId", "operator": "=~", "value": "/^gecko-[0-9]/" },
        { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^b-linux/" }
       ]
      }
     ]
    },
    {
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_workerType",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /^b-linux-gcp/) AND $timeFilter GROUP BY time($interval*2),  \"workerType\" fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "non-gcp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"max\") FROM (SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /^b-linu(x|x-aws)/ AND \"workerType\" !~ /b-linux-gcp/) AND $timeFilter GROUP BY \"workerType\", time($interval*2)  fill(linear)) GROUP BY time($interval*2) fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "!~ /^b-linux-gcp/",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /^b-linu(x|x-aws)/ AND \"workerType\" !~ /b-linux-gcp/) AND $timeFilter GROUP BY \"workerType\", time($interval*2)  fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "graph",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_workerType",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /^b-linux-gcp/) AND $timeFilter GROUP BY time($interval*2),  \"workerType\" fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "non-gcp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"max\") FROM (SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /^b-linu(x|x-aws)/ AND \"workerType\" !~ /b-linux-gcp/) AND $timeFilter GROUP BY \"workerType\", time($interval*2)  fill(linear)) GROUP BY time($interval*2) fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "!~ /^b-linux-gcp/",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /^b-linu(x|x-aws)/ AND \"workerType\" !~ /b-linux-gcp/) AND $timeFilter GROUP BY \"workerType\", time($interval*2)  fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "graph",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_workerType",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /^b-linux-gcp/) AND $timeFilter GROUP BY time($interval*2),  \"workerType\" fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "non-gcp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"max\") FROM (SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /^b-linu(x|x-aws)/ AND \"workerType\" !~ /b-linux-gcp/) AND $timeFilter GROUP BY \"workerType\", time($interval*2)  fill(linear)) GROUP BY time($interval*2) fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "!~ /^b-linux-gcp/",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /^b-linu(x|x-aws)/ AND \"workerType\" !~ /b-linux-gcp/) AND $timeFilter GROUP BY \"workerType\", time($interval*2)  fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Each workerType",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_workerType",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /b-linux-gcp/) AND $timeFilter GROUP BY time($interval*4),  \"workerType\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_workerType",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /b-linux/ AND \"workerType\" !~ /b-linux-gcp/) AND $timeFilter GROUP BY time($interval*4), \"workerType\"  fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_workerType",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /b-linux-gcp/) AND $timeFilter GROUP BY time($interval*4),  \"workerType\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_workerType",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /b-linux/ AND \"workerType\" !~ /b-linux-gcp/) AND $timeFilter GROUP BY time($interval*4), \"workerType\"  fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_workerType",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /b-linux-gcp/) AND $timeFilter GROUP BY time($interval*4),  \"workerType\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_workerType",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"runningWorkers\") FROM \"six_month\".\"tc_web_exec\" WHERE (\"workerType\" =~ /b-linux/ AND \"workerType\" !~ /b-linux-gcp/) AND $timeFilter GROUP BY time($interval*4), \"workerType\"  fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}