{
 "title": "Hardware Worker",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Host",
    "label": "Host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "uptime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "Watched Threads",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "num_threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "LOAD 1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "LOAD 5",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "5 min load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "LOAD 15",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "5 min load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "5 min load",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "Puppet failures",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "puppetagent",
     "query": "SELECT \"time_lastrun\" * 1000 FROM \"six_month\".\"puppetagent\" WHERE (\"host\" =~ /$Host/) AND $timeFilter",
     "select": [
      [
       { "params": [ "events_failure" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "5 min load",
     "measurement": "mem",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "n_users" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "Logging",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "alias": "papertrail activity",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" }
     ],
     "measurement": "papertrail",
     "query": "SELECT sum(\"count\") FROM \"six_month\".\"papertrail\" WHERE (\"host\" =~ /$Host/) AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "io wait",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "used memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "used swap",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "thermal",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "machdep.xcpm.cpu_thermal_level" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "Puppet lastrun",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "measurement": "puppetagent",
     "query": "SELECT \"time_lastrun\" * 1000 FROM \"six_month\".\"puppetagent\" WHERE (\"host\" =~ /$Host/) AND $timeFilter",
     "select": [
      [
       { "params": [ "time_lastrun" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "free memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Logging",
   "type": "graph",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_event",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "event" ], "type": "tag" }
     ],
     "measurement": "papertrail",
     "query": "SELECT sum(\"count\") FROM \"six_month\".\"papertrail\" WHERE (\"host\" =~ /$Host/) AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "Watched Processes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_process_name cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process_name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    },
    {
     "alias": "$tag_process_name threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process_name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "num_threads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    },
    {
     "alias": "$tag_process_name memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process_name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT mean(\"blocked\") FROM \"processes\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "cpu usage",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "user",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT last(\"load5\") FROM \"system\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    },
    {
     "alias": "procstat",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    },
    {
     "alias": "system",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Available RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    },
    {
     "alias": "Cached RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    },
    {
     "alias": "Free RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    },
    {
     "alias": "Used RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"free\") FROM \"mem\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    },
    {
     "alias": "Total RAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used\") FROM \"mem\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    },
    {
     "alias": "Used %",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_path ($tag_fstype on $tag_device)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "fstype" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "Path Used Percent",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  },
  {
   "title": "DiskIO",
   "type": "graph",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    },
    {
     "alias": "Write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$Host/" }
     ]
    }
   ]
  }
 ]
}