{
 "title": "Hardware Workers MacOS",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "provisioner", "query": "releng-hardware" },
   {
    "name": "workerType",
    "query": "SHOW TAG VALUES FROM /tc_queue/ WITH KEY = \"workerType\" WHERE provisionerId =~ /$provisioner/"
   },
   { "name": "Adhoc" }
  ]
 },
 "panels": [
  {
   "title": "Task Start/End",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "tasks" }
   ],
   "targets": [
    {
     "alias": "task start",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "task start" }
     ]
    },
    {
     "alias": "task end",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT sum(\"count\") FROM \"papertrail\" WHERE (\"event\" = 'task end' AND \"host\" =~ /^$host_regex/) AND $timeFilter GROUP BY time($__interval * 10) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "task end" }
     ]
    },
    {
     "alias": "task error",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "task error" }
     ]
    },
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "90s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "no task claimed" }
     ]
    },
    {
     "alias": "change in queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT DERIVATIVE(max(\"pendingTasks\"), 1m) FROM \"tc_queue_exec\" WHERE (\"provisionerId\" =~ /$provisioner/ AND \"workerType\" =~ /$workerType/) AND $timeFilter GROUP BY time($__interval * 2) fill(previous)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "releng-hardware" },
      { "condition": "AND", "key": "workerType", "operator": "=", "value": "gecko-t-linux-talos" }
     ]
    }
   ]
  },
  {
   "title": "Workers Found",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "alias": "$tag_workerType",
     "groupBy": [
      { "params": [ "workerType" ], "type": "tag" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT last(\"workers\"), max(\"workers\"), last(\"workers\") / max(\"workers\") AS \"percent\" FROM \"six_month\".\"tc_queue2_exec\" WHERE (\"provisionerId\" = 'releng-hardware' AND \"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY \"workerType\"",
     "select": [
      [
       { "params": [ "workers" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "releng-hardware" },
      {
       "condition": "AND",
       "key": "workerType",
       "operator": "=~",
       "value": "/gecko-t-(linux-talos|win.*-hw)/"
      }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"running\") AS \"active2\", mean(\"pendingTasks\") AS \"queue\" FROM \"autogen\".\"tc_queue2_exec\" WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval), \"workerType\" fill(null)",
     "select": [
      [
       { "params": [ "workers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "running" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_web_exec",
     "select": [
      [
       { "params": [ "runningWorkers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  },
  {
   "title": "Ronin Puppet",
   "type": "graph",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType failure",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "puppet_ronin_apply_failure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "$tag_workerType success",
     "groupBy": [
      { "params": [ "$__interval * 2" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "puppet_ronin_apply_success",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 2, "w": 14, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType cpu $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       },
       { "params": [ "user" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "$tag_workerType cpu $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       },
       { "params": [ "system" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_workerId $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "workerId" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "thermal",
     "select": [
      [
       { "params": [ "CPU_Speed_Limit" ], "type": "field" },
       { "params": [ "5" ], "type": "bottom" },
       { "params": [ "speed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "$tag_workerId $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "workerId" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "thermal",
     "select": [
      [
       { "params": [ "CPU_Scheduler_Limit" ], "type": "field" },
       { "params": [ "5" ], "type": "bottom" },
       { "params": [ "schd" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  },
  {
   "title": "Deadman",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alerts",
     "query": "SELECT * FROM \"_internal\"..\"database\" LIMIT 10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "alertName", "operator": "=", "value": "RelOps Hardware Deadman" },
      { "condition": "AND", "key": "level", "operator": "=", "value": "CRITICAL" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/mojave|yosemite/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "description": "Max and 95% CPU Temperature",
   "gridPos": { "h": 2, "w": 14, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" }
     ],
     "measurement": "thermal",
     "select": [
      [
       { "params": [ "machdep.xcpm.cpu_thermal_level" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "temp max" ], "type": "alias" }
      ],
      [
       { "params": [ "machdep.xcpm.io_thermal_level" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "io temp max" ], "type": "alias" }
      ],
      [
       { "params": [ "machdep.xcpm.cpu_thermal_level" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       },
       { "params": [ "temp" ], "type": "alias" }
      ],
      [
       { "params": [ "machdep.xcpm.io_thermal_level" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       },
       { "params": [ "io temp" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "description": "Top(10) CPU Temperature C",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerId",
     "groupBy": [
      { "params": [ "$__interval * 100" ], "type": "time" },
      { "params": [ "workerId" ], "type": "tag" }
     ],
     "measurement": "thermal",
     "select": [
      [
       { "params": [ "machdep.xcpm.cpu_thermal_level" ], "type": "field" },
       { "params": [ "10" ], "type": "top" },
       { "params": [ "temp max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  },
  {
   "title": "Deadman",
   "type": "table",
   "gridPos": { "h": 16, "w": 10, "x": 14, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "alerts",
     "query": "SELECT * FROM \"_internal\"..\"database\" LIMIT 10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "log#" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "/(1000*1000*1000)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "alertName", "operator": "=", "value": "RelOps Hardware Deadman" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/mojave|yosemite/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType worker cpu",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "$tag_workerType worker cpu%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType worker mem",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "$tag_workerType worker mem%",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_workerId disk",
     "groupBy": [
      { "params": [ "$__interval * 20" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "workerId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^disk[01]/" }
     ]
    }
   ]
  }
 ]
}