{
 "title": "HW Machine",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "hostname", "query": "acer-002" },
   { "name": "dc", "query": "mdc1,mdc2" }
  ]
 },
 "panels": [
  {
   "title": "Task Start/End",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "task start",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "task start" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$hostname/" }
     ]
    },
    {
     "alias": "task end",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT sum(\"count\") FROM \"papertrail\" WHERE (\"event\" = 'task end' AND \"host\" =~ /^$host_regex/) AND $timeFilter GROUP BY time($__interval * 10) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "task end" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$hostname/" }
     ]
    },
    {
     "alias": "task error",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "task error" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$hostname/" }
     ]
    },
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "90s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "no task claimed" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$hostname/" }
     ]
    },
    {
     "alias": "change in queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT DERIVATIVE(max(\"pendingTasks\"), 1m) FROM \"six_month\".\"tc_queue_exec\" WHERE (\"provisionerId\" =~ /$provisioner/ AND \"workerType\" =~ /$workerType/) AND $timeFilter GROUP BY time($__interval * 2) fill(previous)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "releng-hardware" },
      { "condition": "AND", "key": "workerType", "operator": "=", "value": "gecko-t-linux-talos" }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "workerId", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  },
  {
   "title": "worker process %cpu",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "workerId", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "workerId", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "workerId", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  },
  {
   "title": "Thermal",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "thermal",
     "select": [
      [
       { "params": [ "machdep.xcpm.cpu_thermal_level" ], "type": "field" }
      ],
      [
       { "params": [ "machdep.xcpm.gpu_thermal_level" ], "type": "field" }
      ],
      [
       { "params": [ "machdep.xcpm.io_thermal_level" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "workerId", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  },
  {
   "title": "Thermal Limiting",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "thermal",
     "select": [
      [
       { "params": [ "CPU_Scheduler_Limit" ], "type": "field" }
      ],
      [
       { "params": [ "CPU_Speed_Limit" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "workerId", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_event",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "event" ], "type": "tag" }
     ],
     "measurement": "papertrail",
     "query": "SELECT max(/load1|cpu_usage/) FROM \"six_month\"./system|proc/ WHERE (\"host\" =~ /$hostname/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "/system|proc/",
     "query": "SELECT max(/load1|cpu_usage/) FROM \"six_month\"./system|proc/ WHERE (\"host\" =~ /$hostname/) AND $timeFilter GROUP BY time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "/load/" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "error",
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/task error/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "start",
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "task start" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "alias": "end",
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=~", "value": "/task end/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  },
  {
   "title": "deadman / Logs are live?",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "alertName" ], "type": "tag" },
      { "params": [ "level" ], "type": "tag" }
     ],
     "measurement": "alerts",
     "query": "SELECT \"message\", \"duration\" FROM \"alerts\" WHERE (\"alertName\" = 'RelOps Hardware Deadman' AND \"host\" =~ /$hostname/) AND $timeFilter GROUP BY \"alertName\", \"level\" ORDER BY time DESC",
     "select": [
      [
       { "params": [ "message" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "alertName", "operator": "=", "value": "RelOps Hardware Deadman" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/$hostname/" }
     ]
    }
   ]
  }
 ]
}