{
 "title": "Log Volume",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top max count (spike) for period",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT top(counts, host, host,15) \nFROM (SELECT max(\"count\") AS counts FROM \"six_month\".\"papertrail\" WHERE (\"event\" = 'space' OR \"event\" = 'space taskcluster-workers') AND $timeFilter GROUP BY \"host\")\n\n",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "space" }
     ]
    }
   ]
  },
  {
   "title": "Top 3h count sum",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT top(\"sum\", host, host,5) FROM (SELECT sum(\"count\") FROM \"six_month\".\"papertrail\" WHERE (\"event\" = 'space'OR \"event\" = 'space taskcluster-workers') AND $timeFilter GROUP BY \"host\", time(3h) )\n\n",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "space" }
     ]
    }
   ]
  },
  {
   "title": "Max per host Papertrail [message count]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "max per host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT max(\"count\") FROM \"six_month\".\"papertrail\" WHERE (\"event\" = 'space' OR \"event\" = 'space taskcluster-workers') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "space" },
      { "condition": "OR", "key": "event", "operator": "=", "value": "space taskcluster-workers" }
     ]
    }
   ]
  },
  {
   "title": "Max per host Papertrail [message count]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "max per host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT top(\"sum\", 3) FROM (SELECT sum(\"count\") FROM \"six_month\".\"papertrail\" WHERE (\"event\" = 'space'OR \"event\" = 'space taskcluster-workers') AND $timeFilter GROUP BY \"host\", time($__interval * 10) fill(null)) GROUP BY \"host\", time($__interval * 10)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "space" }
     ]
    }
   ]
  },
  {
   "title": "Total Generic-worker log lines",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "sum",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "generic-worker activity" }
     ]
    },
    {
     "alias": "error",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "task error" }
     ]
    }
   ]
  },
  {
   "title": "Total log lines",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT sum(\"count\") FROM \"six_month\".\"papertrail\" WHERE (\"event\" = 'space' OR \"event\" = 'space taskcluster-workers') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "space" }
     ]
    }
   ]
  },
  {
   "title": "Count of logging hosts (not cloud)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "30m",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT count(distinct(\"count\")) AS count FROM \"six_month\".\"papertrail\" WHERE (\"event\" = 'space') AND (time > now() - 12h) GROUP BY time(30m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "space" }
     ]
    },
    {
     "alias": "1h",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT count(distinct(\"count\")) AS count FROM \"six_month\".\"papertrail\" WHERE (\"event\" = 'space') AND (time > now() - 12h) GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "space" }
     ]
    },
    {
     "alias": "6h",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "query": "SELECT count(distinct(\"count\")) AS count FROM \"six_month\".\"papertrail\" WHERE (\"event\" = 'space') AND (time > now() - 12h) GROUP BY time(6h)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "space" }
     ]
    }
   ]
  },
  {
   "title": "Queue - Running worker count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "total workers",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT max(sum) FROM (SELECT sum(mean) FROM (SELECT mean(\"running\") FROM \"six_month\".\"tc_queue2_exec\" WHERE $timeFilter GROUP BY time(1m), \"workerType\") GROUP BY time(1m)) GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}