{
 "title": "Monitoring Monitoring",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "worker telegraf_relay",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "puppetagent",
     "select": [
      [
       { "params": [ "events_success" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "papertrail telegraf_relay",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "papertrail",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last data",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"workers\") FROM /^tc_/ WHERE $timeFilter GROUP BY time($__interval*10) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") FROM /^tree/ WHERE $timeFilter GROUP BY time($__interval*10) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last data",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"workers\") FROM /^tc_/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"count\") FROM /^papertrail/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cpu_usage\") FROM /^proc/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"status\") FROM /^tree/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"usage_system\") FROM /^cpu/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"load1\") FROM /^system/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"events_failure\") FROM /^puppetagent/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"matching\") FROM /^vcs/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "collection interval",
   "type": "graph",
   "description": "Minutes between data collected.",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT max(\"elapsed\") FROM (SELECT elapsed(\"pendingTasks\",1m) FROM /^tc_queue/ WHERE $timeFilter GROUP BY \"provisionerId\", \"workerType\") GROUP BY \"provisionerId\", time($__interval * 10) fill(null)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       { "params": [ "1h" ], "type": "elapsed" }
      ]
     ]
    }
   ]
  },
  {
   "title": "tc_queue",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 22 },
   "targets": [
    {
     "alias": "$tag_provisionerId",
     "groupBy": [
      { "params": [ "provisionerId" ], "type": "tag" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT last(\"pendingTasks\") FROM \"tc_queue_exec\" WHERE $timeFilter GROUP BY \"provisionerId\"",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "tc_queue2",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 5, "x": 5, "y": 22 },
   "targets": [
    {
     "alias": "$tag_provisionerId",
     "groupBy": [
      { "params": [ "provisionerId" ], "type": "tag" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT last(\"pendingTasks\") FROM \"tc_queue2_exec\" WHERE $timeFilter GROUP BY \"provisionerId\"",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "tc_web",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 5, "x": 10, "y": 22 },
   "targets": [
    {
     "alias": "$tag_provisionerId",
     "groupBy": [
      { "params": [ "provisionerId" ], "type": "tag" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT last(\"pendingTasks\") FROM \"tc_web_exec\" WHERE $timeFilter GROUP BY \"provisionerId\"",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}