{
 "title": "moonshot vs aws vismet",
 "time": { "from": "2021-09-28T11:17:48.207Z", "to": "2021-10-03T10:45:15.399Z" },
 "templating": {
  "list": [
   { "name": "adhoc" },
   {
    "name": "measure",
    "query": "SpeedIndex,FirstVisualChange,PerceptualSpeedIndex,LastVisualChange,ContentfulSpeedIndex"
   },
   {
    "name": "suite",
    "query": "SHOW TAG VALUES FROM perftest WITH KEY = \"suite\""
   }
  ]
 },
 "panels": [
  {
   "title": "mean stddev Moonshot hardware",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_suite",
     "query": "SELECT mean(\"stddev\") FROM (SELECT stddev(\"$measure\") /mean(\"$measure\") as \"stddev\" FROM \"perftest\" WHERE \"instance_type\" = 'moonshot' AND $timeFilter GROUP BY \"suite\", \"instance_type\" fill(null))"
    }
   ]
  },
  {
   "title": "sum stddev Moonshot hardware",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_suite",
     "query": "SELECT \"stddev\" FROM (SELECT stddev(\"$measure\") /mean(\"$measure\") as \"stddev\" FROM \"perftest\" WHERE \"instance_type\" = 'moonshot' AND $timeFilter GROUP BY \"suite\", \"instance_type\" fill(null))"
    }
   ]
  },
  {
   "title": "mean stddev g4dn.2xlarge",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_suite",
     "query": "SELECT mean(\"stddev\") FROM (SELECT stddev(\"$measure\") /mean(\"$measure\") as \"stddev\" FROM \"perftest\" WHERE ((\"instance_type\" != 'moonshot' AND \"instance_type\" != 'g4dn.xlarge' ) OR \"instance_type\" = 'g4dn.2xlarge') AND $timeFilter GROUP BY \"suite\" fill(null))"
    }
   ]
  },
  {
   "title": "sum stddev g4dn.2xlarge",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_suite",
     "query": "SELECT \"stddev\" FROM (SELECT stddev(\"$measure\") /mean(\"$measure\") as \"stddev\" FROM \"perftest\" WHERE ((\"instance_type\" != 'moonshot' AND \"instance_type\" != 'g4dn.xlarge' ) OR \"instance_type\" = 'g4dn.2xlarge') AND $timeFilter GROUP BY \"suite\" fill(null))"
    }
   ]
  },
  {
   "title": "mean stddev g4dn.xlarge",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_suite",
     "query": "SELECT mean(\"stddev\") FROM (SELECT stddev(\"$measure\") /mean(\"$measure\") as \"stddev\" FROM \"perftest\" WHERE \"instance_type\" != 'moonshot' AND \"instance_type\" = 'g4dn.xlarge'  AND $timeFilter GROUP BY \"suite\" fill(null))"
    }
   ]
  },
  {
   "title": "sum stddev g4dn.xlarge",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$tag_suite",
     "query": "SELECT \"stddev\" FROM (SELECT stddev(\"$measure\") /mean(\"$measure\") as \"stddev\" FROM \"perftest\" WHERE \"instance_type\" != 'moonshot' AND \"instance_type\" = 'g4dn.xlarge'  AND $timeFilter GROUP BY \"suite\" fill(null))"
    }
   ]
  },
  {
   "title": "mean stddev Moonshot hardware",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_suite",
     "query": "SELECT mean(\"stddev\") FROM (SELECT stddev(\"$measure\") /mean(\"$measure\") as \"stddev\" FROM \"perftest\" WHERE \"instance_type\" = 'moonshot' AND $timeFilter GROUP BY \"suite\", \"instance_type\" fill(null)) GROUP BY \"suite\""
    }
   ]
  },
  {
   "title": "mean stddev AWS vm",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_suite",
     "query": "SELECT mean(\"stddev\") FROM (SELECT stddev(\"$measure\") /mean(\"$measure\") as \"stddev\" FROM \"perftest\" WHERE ((\"instance_type\" != 'moonshot' AND \"instance_type\" != 'g4dn.xlarge' ) OR \"instance_type\" = 'g4dn.2xlarge') AND $timeFilter GROUP BY \"suite\" fill(null)) GROUP BY \"suite\""
    }
   ]
  },
  {
   "title": "mean stddev g4dn.xlarge",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_suite",
     "query": "SELECT mean(\"stddev\") FROM (SELECT stddev(\"$measure\") /mean(\"$measure\") as \"stddev\" FROM \"perftest\" WHERE \"instance_type\" != 'moonshot' AND \"instance_type\" = 'g4dn.xlarge'  AND $timeFilter GROUP BY \"suite\" fill(null)) GROUP BY \"suite\""
    }
   ]
  },
  {
   "title": "test count",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_suite",
     "query": "SELECT  count($measure) FROM \"perftest\" WHERE \"instance_type\" = 'moonshot' AND $timeFilter GROUP BY  \"suite\""
    }
   ]
  },
  {
   "title": "stddev Moonshot hardware",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_suite",
     "query": "SELECT  stddev($measure) FROM \"perftest\" WHERE \"instance_type\" = 'moonshot' AND $timeFilter GROUP BY  \"suite\""
    }
   ]
  },
  {
   "title": "test count",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_suite",
     "query": "SELECT  count($measure) FROM \"perftest\" WHERE ((\"instance_type\" != 'moonshot' AND \"instance_type\" != 'g4dn.xlarge' ) OR \"instance_type\" = 'g4dn.2xlarge') AND $timeFilter GROUP BY  \"suite\""
    }
   ]
  },
  {
   "title": "stddev g4dn.2xlarge",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_suite",
     "query": "SELECT  stddev(\"$measure\") FROM \"perftest\" WHERE ((\"instance_type\" != 'moonshot' AND \"instance_type\" != 'g4dn.xlarge' ) OR \"instance_type\" = 'g4dn.2xlarge') AND $timeFilter GROUP BY  \"suite\""
    }
   ]
  },
  {
   "title": "test count",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_suite",
     "query": "SELECT  count($measure) FROM \"perftest\" WHERE \"instance_type\" != 'moonshot' AND \"instance_type\" = 'g4dn.xlarge' AND $timeFilter GROUP BY  \"suite\""
    }
   ]
  },
  {
   "title": "stddev g4dn.xlarge",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_suite",
     "query": "SELECT  stddev(\"$measure\") FROM \"perftest\" WHERE \"instance_type\" != 'moonshot' AND \"instance_type\" = 'g4dn.xlarge'  AND $timeFilter GROUP BY  \"suite\""
    }
   ]
  },
  {
   "title": "Moonshot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "SELECT $measure FROM \"perftest\" WHERE \"instance_type\" = 'moonshot' AND $timeFilter GROUP BY \"instance_type\", \"suite\""
    }
   ]
  },
  {
   "title": "g4dn.2xlarge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "query": "SELECT \"$measure\" FROM \"perftest\" WHERE ((\"instance_type\" != 'moonshot' AND \"instance_type\" != 'g4dn.xlarge' ) OR \"instance_type\" = 'g4dn.2xlarge') AND $timeFilter GROUP BY \"suite\""
    }
   ]
  },
  {
   "title": "g4dn.xlarge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "query": "SELECT \"$measure\" FROM \"perftest\" WHERE \"instance_type\" != 'moonshot' AND \"instance_type\" = 'g4dn.xlarge' AND $timeFilter GROUP BY \"suite\""
    }
   ]
  },
  {
   "type": "histogram",
   "description": "$suite",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 34 },
   "repeat": "suite",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT $measure FROM \"perftest\" WHERE \"instance_type\" = 'moonshot' AND \"suite\" = '$suite' AND $timeFilter GROUP BY \"suite\""
    }
   ]
  },
  {
   "type": "histogram",
   "description": "$suite",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 34 },
   "repeat": "suite",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT $measure FROM \"perftest\" WHERE ((\"instance_type\" != 'moonshot' AND \"instance_type\" != 'g4dn.xlarge' ) OR \"instance_type\" = 'g4dn.2xlarge')  AND \"suite\" = '$suite' AND $timeFilter GROUP BY \"suite\""
    }
   ]
  },
  {
   "type": "histogram",
   "description": "$suite",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 34 },
   "repeat": "suite",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT $measure FROM \"perftest\" WHERE \"instance_type\" = 'g4dn.xlarge'  AND \"suite\" = '$suite' AND $timeFilter GROUP BY \"suite\""
    }
   ]
  }
 ]
}