{
 "title": "Moonshot",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "adhoc" },
   {
    "name": "workerType",
    "query": "SHOW TAG VALUES FROM /tc_queue/ WITH KEY = \"workerType\" WHERE provisionerId = 'releng-hardware'"
   }
  ]
 },
 "panels": [
  {
   "title": "Workers Found (current/(180day max))",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "$tag_workerType",
     "groupBy": [
      { "params": [ "workerType" ], "type": "tag" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT last(\"workers\") / max(\"workers\") FROM \"six_month\".\"tc_queue2_exec\" WHERE (\"provisionerId\" = 'releng-hardware' AND \"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY \"workerType\"",
     "select": [
      [
       { "params": [ "workers" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "releng-hardware" },
      {
       "condition": "AND",
       "key": "workerType",
       "operator": "=~",
       "value": "/gecko-t-(linux-talos|win.*-hw)/"
      }
     ]
    }
   ]
  },
  {
   "title": "no-ping/hung",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "systemcheck",
     "select": [
      [
       { "params": [ "noping" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "no ping" ], "type": "alias" }
      ],
      [
       { "params": [ "hung" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "hung" ], "type": "alias" }
      ],
      [
       { "params": [ "missing" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "missing" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Workers Found",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT (mean(\"workers\") - mean(\"quarantined\")) AS \"workers\" FROM \"tc_queue2_exec\" WHERE \"provisionerId\" = 'releng-hardware' AND \"workerType\" =~ /^$workerType$/ AND $timeFilter GROUP BY time($__interval * 10), \"workerType\" fill(previous)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "workers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "running" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" },
      { "condition": "AND", "key": "provisionerId", "operator": "=", "value": "releng-hardware" }
     ]
    }
   ]
  },
  {
   "title": "WorkerType Not found",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "linux",
     "measurement": "systemcheck",
     "query": "SELECT sum(\"missing\") AS \"missing\" FROM \"six_month\".\"systemcheck\" WHERE (\"host\" =~ /^t-linux/) AND $timeFilter GROUP BY time(30m)",
     "select": [
      [
       { "params": [ "missing" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "missing" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^t-linux/" }
     ]
    },
    {
     "alias": "windows",
     "measurement": "systemcheck",
     "query": "SELECT sum(\"missing\") AS \"missing\" FROM \"six_month\".\"systemcheck\" WHERE (\"host\" !~ /^t-linux/) AND $timeFilter GROUP BY time(30m)",
     "select": [
      [
       { "params": [ "missing" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "missing" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "!~", "value": "/^t-linux/" }
     ]
    }
   ]
  },
  {
   "title": "WorkerType Not found",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "chassis" ], "type": "tag" },
      { "params": [ "cart" ], "type": "tag" },
      { "params": [ "workerId" ], "type": "tag" }
     ],
     "measurement": "systemcheck",
     "query": "SELECT sum(\"missing\") AS \"missing\" FROM \"six_month\".\"systemcheck\" WHERE $timeFilter GROUP BY \"chassis\", \"cart\", \"workerId\"",
     "select": [
      [
       { "params": [ "missing" ], "type": "field" },
       { "params": [ "missing" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "event", "operator": "=", "value": "missing" }
     ]
    }
   ]
  },
  {
   "title": "History",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT (max(\"workers\") - max(\"quarantined\")) AS \"workers\" FROM \"tc_queue2_exec\" WHERE \"provisionerId\" = 'releng-hardware' AND \"workerType\" =~ /^$workerType$/ AND $timeFilter GROUP BY time(1h), \"workerType\" fill(previous)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "workers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "running" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" },
      { "condition": "AND", "key": "provisionerId", "operator": "=", "value": "releng-hardware" }
     ]
    }
   ]
  },
  {
   "title": "no-ping/hung",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "chassis" ], "type": "tag" },
      { "params": [ "cart" ], "type": "tag" },
      { "params": [ "workerId" ], "type": "tag" }
     ],
     "measurement": "systemcheck",
     "select": [
      [
       { "params": [ "noping" ], "type": "field" },
       { "params": [ "no ping" ], "type": "alias" }
      ],
      [
       { "params": [ "hung" ], "type": "field" },
       { "params": [ "hung" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Workers vs Active",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"pendingTasks\") AS \"queue\", mean(\"running\") AS \"active\", (mean(\"workers\") - mean(\"quarantined\")) AS \"workers\", mean(\"quarantined\") AS \"quarantined\" FROM \"tc_queue2_exec\" WHERE (\"workerType\" =~ /^$workerType$/ AND \"provisionerId\" = 'releng-hardware') AND $timeFilter GROUP BY time($__interval * 10), \"workerType\" fill(none)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "workers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "running" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" },
      { "condition": "AND", "key": "provisionerId", "operator": "=", "value": "releng-hardware" }
     ]
    }
   ]
  },
  {
   "title": "worker count (from cpu_usage counts)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat",
     "query": "SELECT count(\"count\") FROM (SELECT count(\"cpu_usage\") FROM \"procstat\" WHERE (\"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval), \"workerType\", \"host\", \"dataCenter\" fill(null)) GROUP BY time($__interval), \"workerType\", \"dataCenter\"",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dataCenter" ], "type": "tag" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "procstat_lookup",
     "query": "SELECT count(\"mean\") FROM (SELECT mean(\"running\") FROM \"procstat_lookup\" WHERE (\"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval), \"dataCenter\", \"workerType\", \"host\" fill(null)) GROUP BY time($__interval), \"dataCenter\", \"workerType\" fill(null)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dataCenter" ], "type": "tag" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT count(\"count\") FROM (SELECT count(\"usage_user\") FROM \"cpu\" WHERE (\"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval), \"dataCenter\", \"workerType\", \"host\" fill(null)) GROUP BY time($__interval), \"dataCenter\", \"workerType\" fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "hung chassis $tag_chassis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "chassis" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "systemcheck",
     "query": "SELECT count(\"mean\") FROM (SELECT mean(\"hung\") FROM \"systemcheck\" WHERE $timeFilter GROUP BY time($__interval), \"chassis\", \"id\" fill(null)) GROUP BY time($__interval), \"chassis\" fill(null)",
     "select": [
      [
       { "params": [ "hung" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "repeat no-ping/hung",
   "type": "table-old",
   "description": "Sum of events for hostnames over the last 4 weeks.",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "4w" ], "type": "time" },
      { "params": [ "chassis" ], "type": "tag" },
      { "params": [ "cart" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "systemcheck",
     "select": [
      [
       { "params": [ "noping" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "no ping" ], "type": "alias" }
      ],
      [
       { "params": [ "hung" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "hung" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "chassis total no-ping/hung",
   "type": "graph",
   "description": "Sum of hung for each chassis.",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_chassis",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "chassis" ], "type": "tag" }
     ],
     "measurement": "systemcheck",
     "select": [
      [
       { "params": [ "hung" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "hung" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "host id heatmap",
   "type": "heatmap",
   "description": "Buckets by id number.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "alias": "$tag_workerId",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "workerId" ], "type": "tag" }
     ],
     "measurement": "systemcheck",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "host id heatmap",
   "type": "heatmap",
   "description": "Buckets by id number.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "alias": "$tag_workerId",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "workerId" ], "type": "tag" }
     ],
     "measurement": "systemcheck",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  }
 ]
}