{
 "title": "VCS-Sync",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "vcs-sync gecko-dev",
   "type": "graph",
   "description": "gecko-dev not matching mozilla-central",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vcssync_exec",
     "query": "SELECT 1.0 - mean(\"matching\") FROM \"six_months\".\"vcssync_exec\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "matching" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "vcs-sync gecko-dev",
   "type": "graph",
   "description": "gecko-dev not matching mozilla-central",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vcssync_exec",
     "query": "SELECT 1.0 - mean(\"matching\") FROM \"vcssync_exec\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "matching" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "repo", "operator": "=", "value": "mozilla-central" }
     ]
    }
   ]
  },
  {
   "title": "mozilla-central commits",
   "type": "table",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo" ], "type": "tag" }
     ],
     "measurement": "vcssync_exec",
     "select": [
      [
       { "params": [ "message" ], "type": "field" }
      ],
      [
       { "params": [ "name" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "repo", "operator": "=", "value": "mozilla-central" }
     ]
    }
   ]
  },
  {
   "title": "Tree Closures",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "who" ], "type": "tag" },
      { "params": [ "reason" ], "type": "tag" },
      { "params": [ "repo" ], "type": "tag" }
     ],
     "measurement": "treestatus_stack_exec",
     "select": [
      [
       { "params": [ "status_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "repo",
       "operator": "=~",
       "value": "/mozilla-central|mozilla-release|mozilla-beta$/"
      }
     ]
    }
   ]
  }
 ]
}