{
 "title": "[WIP] DC Usage Copy",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "provisioner",
    "query": "SHOW TAG VALUES FROM /tc_queue/ WITH KEY = \"provisionerId\" "
   },
   {
    "name": "workerType",
    "query": "SHOW TAG VALUES FROM /tc_queue/ WITH KEY = \"workerType\" WHERE provisionerId =~ /$provisioner/ "
   },
   { "name": "targetCount", "label": "target count", "query": "190" }
  ]
 },
 "panels": [
  {
   "title": "Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "_ $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT max(\"pendingTasks\") - max(\"running\") as \"next\" FROM \"tc_queue2_exec\" WHERE \"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/ AND $timeFilter GROUP BY \"provisionerId\", \"workerType\", time($interval) fill(null)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "releng-hardware" }
     ]
    },
    {
     "alias": ". $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT integral(\"running\", 20m), max(\"pendingTasks\") + max(\"running\") as \"total\", max(\"pendingTasks\") as \"queued\", max(\"running\") as \"running\" FROM \"tc_queue2_exec\" WHERE \"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/ AND $timeFilter GROUP BY \"provisionerId\", \"workerType\", time($interval) fill(null)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=", "value": "releng-hardware" }
     ]
    }
   ]
  },
  {
   "title": "Time research",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Usage (logged)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "20m $col",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "papertrail",
       "query": "SELECT count(\"count\") FROM (SELECT count(\"count\") FROM \"papertrail\" WHERE \"event\" = 'task' AND $timeFilter GROUP BY \"host\", time(20m) fill(none)) GROUP BY time(20m) fill(previous)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "event", "operator": "=~", "value": "/^no task/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
       ]
      },
      {
       "alias": "30m $col",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "papertrail",
       "query": "SELECT count(\"count\") FROM (SELECT count(\"count\") FROM \"papertrail\" WHERE \"event\" = 'task' AND $timeFilter GROUP BY \"host\", time(30m) fill(none)) GROUP BY time(30m) fill(linear)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "event", "operator": "=~", "value": "/^no task/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
       ]
      },
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "papertrail",
       "query": "SELECT count(\"count\") FROM (SELECT count(\"count\") FROM \"papertrail\" WHERE \"event\" = 'task' AND $timeFilter GROUP BY \"host\", time(12h) fill(none)) GROUP BY time(12h)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "event", "operator": "=~", "value": "/^no task/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "task logged",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_event",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "papertrail",
       "query": "SELECT count(\"count\") FROM \"papertrail\" WHERE \"event\" = 'no task' OR \"event\" = 'task' AND $timeFilter GROUP BY \"event\", time(10m)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "event", "operator": "=~", "value": "/^no task/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^tc_queue/",
       "query": "SELECT mean(\"running\") as \"tc count\", mean(\"pendingTasks\") as \"queue\" FROM /^tc_queue/ WHERE (\"provisionerId\" = 'releng-hardware') AND $timeFilter GROUP BY time(5m) fill(previous)",
       "select": [
        [
         { "params": [ "running" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "pendingTasks" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "provisionerId", "operator": "=", "value": "releng-hardware" }
       ]
      }
     ]
    },
    {
     "title": "worker process",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_workerType",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "workerType" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "cpu_usage" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "process_name", "operator": "=", "value": "generic-worker" }
       ]
      }
     ]
    },
    {
     "title": "Usage (logged)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "10m $col $tag_event",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "papertrail",
       "query": "SELECT max(\"count\"), mean(\"count\"), ((max(\"count\") + mean(\"count\"))/2)as \"level\" FROM (SELECT count(\"count\") FROM \"papertrail\" WHERE (\"event\" = 'no task' OR \"event\" = 'task') AND $timeFilter GROUP BY \"event\", time(1m) fill(none)) GROUP BY \"event\", time(10m)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "event", "operator": "=~", "value": "/^no task/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
       ]
      },
      {
       "alias": "daily $col $tag_event",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "papertrail",
       "query": "SELECT mean(\"mean\"), max(\"max\") FROM (SELECT max(\"count\"), mean(\"count\") FROM (SELECT count(\"count\") FROM \"papertrail\" WHERE (\"event\" = 'no task' OR \"event\" = 'task') AND $timeFilter GROUP BY \"event\", time(1m) fill(none)) GROUP BY \"event\", time(10m)) GROUP BY \"event\", time(3h)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "event", "operator": "=~", "value": "/^no task/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
       ]
      }
     ]
    },
    {
     "title": "worker logging",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "datacenter",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "papertrail",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "event", "operator": "=~", "value": "/worker activity/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
       ]
      },
      {
       "alias": "cloud",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "papertrail",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "event", "operator": "=~", "value": "/worker activity/" },
        { "condition": "AND", "key": "host", "operator": "!~", "value": "/mdc[0-9].mozilla.com$/" }
       ]
      },
      {
       "alias": "datacenter all",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "papertrail",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "event", "operator": "=", "value": "space" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/mdc[0-9].mozilla.com$/" }
       ]
      },
      {
       "alias": "cloud all",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "papertrail",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "event", "operator": "=", "value": "space" },
        { "condition": "AND", "key": "host", "operator": "!~", "value": "/mdc[0-9].mozilla.com$/" }
       ]
      }
     ]
    },
    {
     "title": "DC Instances",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "hardware workers",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT sum(\"value\") FROM (SELECT mean(\"workers\") as \"value\" FROM \"tc_queue_exec\" WHERE (\"provisionerId\" = 'releng-hardware') AND \"workerType\" !~ /gamma$/ AND $timeFilter GROUP BY time(1d), \"provisionerId\", \"workerType\" fill(null)) GROUP BY time(1d) fill(previous)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}