{
 "title": "Workers [WIP]",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "provisioner",
    "query": "SHOW TAG VALUES FROM six_month./tc_queue/ WITH KEY = \"provisionerId\" "
   },
   {
    "name": "workerType",
    "query": "SHOW TAG VALUES FROM six_month./tc_queue/ WITH KEY = \"workerType\" WHERE provisionerId =~ /$provisioner/ "
   },
   { "name": "Adhoc" }
  ]
 },
 "panels": [
  {
   "title": "Last Task Status",
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "tasks" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"failed\") AS \"failed\", mean(\"exception\") AS \"exception\", mean(\"completed\") AS \"completed\" FROM \"one_week\"./tc_queue/,\"six_month\"./tc_queue/ WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval * 10), \"workerType\", \"provisionerId\" fill(none)",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "failed" ], "type": "alias" }
      ],
      [
       { "params": [ "exception" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "exception" ], "type": "alias" }
      ],
      [
       { "params": [ "completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "completed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  },
  {
   "title": "Cloud",
   "type": "table",
   "description": "See <https://hg.mozilla.org/ci/ci-configuration/file/tip/worker-pools.yml> for setting scaling pool configuration.",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT (0 + LAST(\"pendingTasks\")) AS \"queue\", LAST(\"running\") AS \"active\",  (LAST(\"pendingTasks\") / LAST(\"active\")) AS \"lazy\", LAST(\"quarantined\") AS \"quarantined\", LAST(\"quarantined\") / LAST(\"workers\") AS \"percent quarantined\", mean(\"exception\") AS \"exception\", mean(\"failed\") AS \"failed\", mean(\"completed\") AS \"success\", 1.0 - mean(\"completed\") / (mean(\"exception\") + mean(\"failed\") + mean(\"completed\")) as \"percent failed\" FROM \"one_week\".\"tc_queue2_exec\",\"six_month\".\"tc_queue2_exec\" WHERE (\"provisionerId\" = 'aws-provisioner-v1' OR \"provisionerId\" =~ /^gecko/  OR \"provisionerId\" =~ /^scriptworker-prov/) AND \"workerType\" =~ /^$workerType$/ AND \"provisionerId\" =~ /^$provisioner$/ AND $timeFilter GROUP BY provisionerId, workerType",
     "select": [
      [
       { "params": [ "workers" ], "type": "field" }
      ],
      [
       { "params": [ "quarantinedWorkers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" },
      { "condition": "AND", "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" }
     ]
    }
   ]
  },
  {
   "title": "TC Worker Backlog/Workers",
   "type": "graph",
   "description": "= Queued tasks / workers running tasks\nfiltered to:\nreleng-hardware\naws-provisioner-v1 with /^(mobile|app-services|gecko)-/\nterraform-packet",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "task overload" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $tag_provisionerId $col",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"pendingTasks\") / (mean(\"running\")) as \"runner load\" FROM /^tc_queue/ WHERE $timeFilter AND \"provisionerId\" = 'proj-autophone' AND \"workerType\" != '' AND (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) GROUP BY time($__interval * 10), \"workerType\", \"provisionerId\" fill(1)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/.*win7.*gpu/" }
     ]
    }
   ]
  },
  {
   "title": "Workers vs Active",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $tag_provisionerId $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"running\") AS \"active\", (mean(\"workers\") - mean(\"quarantined\")) AS \"workers\", mean(\"quarantined\") AS \"quarantined\" FROM /^tc_queue/ WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/ AND \"provisionerId\" != 'aws-provisioner-v1' AND \"provisionerId\" !~ /^gecko/) AND $timeFilter GROUP BY time($__interval * 10), \"provisionerId\", \"workerType\" fill(none)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "workers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "running" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" },
      { "condition": "AND", "key": "provisionerId", "operator": "=", "value": "releng-hardware" }
     ]
    },
    {
     "alias": "$tag_workerType $tag_provisionerId $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tc_web_exec",
     "query": "SELECT mean(\"runningWorkers\") AS \"active\" FROM /^tc_web/ WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/ AND \"provisionerId\" != 'releng-hardware') AND $timeFilter GROUP BY time($__interval * 10), \"workerType\", \"provisionerId\" fill(none)",
     "select": [
      [
       { "params": [ "runningWorkers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" },
      { "condition": "AND", "key": "provisionerId", "operator": "!=", "value": "releng-hardware" }
     ]
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT (0 + LAST(\"pendingTasks\")) AS \"queue\", LAST(\"running\") AS \"active\", LAST(\"idle\") AS \"idle\", LAST(\"workers\") AS \"workers\",  (LAST(\"pendingTasks\") / LAST(\"workers\")) * (MEAN(\"idle\") / LAST(\"workers\")) AS \"lazy\", LAST(\"quarantined\") AS \"quarantined\", LAST(\"quarantined\") / LAST(\"workers\") AS \"percent quarantined\", mean(\"exception\") AS \"exception\", mean(\"failed\") AS \"failed\", mean(\"completed\") AS \"success\", 1.0 - mean(\"completed\") / (mean(\"exception\") + mean(\"failed\") + mean(\"completed\")) as \"percent failed\" FROM \"one_week\".\"tc_queue2_exec\",\"six_month\".\"tc_queue2_exec\" WHERE \"provisionerId\" != 'aws-provisioner-v1' AND \"provisionerId\" != 'gce' AND \"provisionerId\" !~ /^gecko/ AND \"provisionerId\" !~ /^scriptworker/ AND \"provisionerId\" !~ /^bitbar/ AND \"provisionerId\" != 'proj-autophone' AND \"provisionerId\" != 'terraform-packet' AND \"workerType\" =~ /^$workerType$/ AND \"provisionerId\" =~ /^$provisioner$/ AND $timeFilter GROUP BY provisionerId, workerType",
     "select": [
      [
       { "params": [ "workers" ], "type": "field" }
      ],
      [
       { "params": [ "quarantinedWorkers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" },
      { "condition": "AND", "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "workerType" ], "type": "tag" }
     ],
     "measurement": "tc_web_exec",
     "query": "SELECT last(\"runningWorkers\") AS \"active\", last(\"workers\") AS \"workers\", last(\"pendingTasks\") AS \"queue\", last(\"idleWorkers\") AS \"idle\" FROM \"six_month\".\"tc_web_exec\" WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/ AND (\"provisionerId\" = 'bitbar' OR \"provisionerId\" = 'proj-autophone' OR \"provisionerId\" = 'terraform-packet')) AND $timeFilter GROUP BY \"provisionerId\", \"workerType\"",
     "select": [
      [
       { "params": [ "runningWorkers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "workers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "workers" ], "type": "alias" }
      ],
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "queue" ], "type": "alias" }
      ],
      [
       { "params": [ "idleWorkers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "idle" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" },
      { "condition": "AND", "key": "provisionerId", "operator": "=", "value": "bitbar" }
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "graph",
   "description": "<https://wiki.mozilla.org/CIDuty/How_To/High_Pending_Counts>",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "queued tasks" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $tag_provisionerId $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT mean(\"pendingTasks\") AS \"queue\" FROM /^tc_queue/ WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval), \"workerType\", \"provisionerId\" fill(none)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "$tag_workerType $tag_provisionerId $col alert",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT mean(\"pendingTasks\") AS \"queue\" FROM /^tc_queue_exec/ WHERE $timeFilter GROUP BY time($__interval), \"workerType\", \"provisionerId\" fill(none)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active vs Queue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_web_exec",
     "query": "SELECT mean(\"runningWorkers\") AS \"active\", mean(\"pendingTasks\") AS \"queue\" FROM /^tc_web/ WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval * 10), \"workerType\", \"provisionerId\" fill(previous)",
     "select": [
      [
       { "params": [ "runningWorkers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT mean(\"pendingTasks\") AS \"queue\" FROM /^tc_queue/ WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval), \"workerType\", \"provisionerId\" fill(linear)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  },
  {
   "title": "Ronin Puppet",
   "type": "graph",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType failure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "puppet_ronin_apply_failure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "$tag_workerType success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "puppet_ronin_apply_success",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active vs Queue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "workers" }
   ],
   "targets": [
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval * 10" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tc_web_exec",
     "query": "SELECT mean(\"runningWorkers\") AS \"active\", mean(\"pendingTasks\") AS \"queue\" FROM /^tc_web/ WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval * 10), \"workerType\", \"provisionerId\" fill(previous)",
     "select": [
      [
       { "params": [ "runningWorkers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    },
    {
     "alias": "$tag_workerType $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tc_queue_exec",
     "query": "SELECT mean(\"pendingTasks\") AS \"queue\" FROM /^tc_queue/ WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/) AND $timeFilter GROUP BY time($__interval), \"workerType\", \"provisionerId\" fill(linear)",
     "select": [
      [
       { "params": [ "pendingTasks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queue" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^$provisioner$/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  }
 ]
}