{
 "title": "Workers Missing",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "provisioner", "query": "releng-hardware" },
   { "name": "workerType", "query": "gecko-t-osx-1014" }
  ]
 },
 "panels": [
  {
   "title": "worker count",
   "type": "graph",
   "description": "Count of workers for workerType from Taskcluster Queue API",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"running\") AS \"active\", (mean(\"workers\") - mean(\"quarantined\")) AS \"workers\", mean(\"quarantined\") AS \"quarantined\" FROM \"one_week\"./tc_queue/,\"six_month\"./tc_queue/ WHERE (\"provisionerId\" =~ /^$provisioner$/ AND \"workerType\" =~ /^$workerType$/ AND \"provisionerId\" != 'aws-provisioner-v1' AND \"provisionerId\" !~ /^gecko/) AND $timeFilter GROUP BY time($__interval * 10), \"provisionerId\", \"workerType\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last procstat",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "6h" ], "type": "time" },
      { "params": [ "workerId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"distinct\") AS \"workerId\" FROM (SELECT distinct(\"host\") FROM (SELECT \"cpu_usage\", \"host\" FROM \"six_month\".\"procstat\" WHERE $timeFilter AND \"workerType\" =~ /^$workerType$/) GROUP BY time(6h) fill(null)) GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "workerType", "operator": "=~", "value": "/^$workerType$/" }
     ]
    }
   ]
  },
  {
   "title": "Last puppet report",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "workerId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "puppet_ronin_apply_durations",
     "query": "SELECT last(\"distinct\") FROM (SELECT distinct(\"workerId\") FROM (SELECT \"value\", \"workerId\" FROM \"six_month\".\"puppet_ronin_apply_durations\" WHERE $timeFilter AND \"workerType\" =~ /^$workerType$/ ) GROUP BY time(6h) fill(null)) GROUP BY \"workerId\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}