{
 "title": "worker-manager",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter" }
  ]
 },
 "panels": [
  { "title": "Max", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Type Max",
   "type": "table",
   "description": "Sum of max for each instance type:\nsum( maxCapacity / capacityPerInstance FROM worker_manager GROUP BY workerPool, instance_type ) GROUP BY instance_type",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$tag_instance_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worker_manager",
     "query": "SELECT sum(\"max\") FROM (SELECT last(\"maxCapacity\") / last(\"capacityPerInstance\") AS \"max\" FROM \"worker_manager\" WHERE $timeFilter GROUP BY time(1d), \"workerPool\", \"instance_type\" fill(previous)) GROUP BY time(1d), \"instance_type\" fill(previous)",
     "select": [
      [
       { "params": [ "capacityPerInstance" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "maxCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WorkerType Instance Types",
   "type": "table",
   "description": "Sum of max for each instance type:\nsum( maxCapacity / capacityPerInstance FROM worker_manager GROUP BY workerPool, instance_type ) GROUP BY instance_type",
   "gridPos": { "h": 13, "w": 7, "x": 6, "y": 1 },
   "targets": [
    {
     "alias": "$tag_workerPool $tag_instance_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "worker_manager",
     "query": "SELECT last(\"maxCapacity\") / last(\"capacityPerInstance\") AS \"max\" FROM \"worker_manager\" WHERE $timeFilter AND \"instance_type\" != '' GROUP BY time(1d), \"workerPool\", \"instance_type\" fill(previous)",
     "select": [
      [
       { "params": [ "capacityPerInstance" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "maxCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WorkerType Max",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_workerPool",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerPool" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "worker_manager",
     "select": [
      [
       { "params": [ "maxCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Running", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "WorkerType Running",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_provider $tag_workerPool",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "workerPool" ], "type": "tag" },
      { "params": [ "provider" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "worker_manager",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AWS EC2 Daily runInstance calls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{Action}}",
     "dimensions": { "Action": "RunInstances" },
     "metricName": "SuccessfulCalls",
     "namespace": "AWS/EC2/API",
     "period": "1d",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "queue api - running workers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_provisionerId/$tag_workerType",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "provisionerId" ], "type": "tag" },
      { "params": [ "workerType" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_queue2_exec",
     "query": "SELECT mean(\"running\") FROM \"six_month\".\"tc_queue2_exec\" WHERE (\"provisionerId\" =~ /^gecko-[0-9]/ AND \"workerType\" =~ /^b-linux/) AND $timeFilter GROUP BY time($__interval), \"provisionerId\", \"workerType\" fill(null) ",
     "region": "default",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "statistics": [ "Average" ],
     "tags": [
      { "key": "provisionerId", "operator": "=~", "value": "/^gecko-[0-9]/" },
      { "condition": "AND", "key": "workerType", "operator": "=~", "value": "/^b-linux/" }
     ]
    }
   ]
  },
  {
   "title": "GCP count (1month retention)",
   "type": "graph",
   "description": "https://console.cloud.google.com/monitoring/metrics-explorer?organizationId=442341870013&project=fxci-production-logging&supportedpurview=project&pageState=%7B%22xyChart%22:%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22compute.googleapis.com%2Finstance%2Fcpu%2Freserved_cores%5C%22%20resource.type%3D%5C%22gce_instance%5C%22%22,%22minAlignmentPeriod%22:%2260s%22,%22unitOverride%22:%221%22,%22aggregations%22:%5B%7B%22perSeriesAligner%22:%22ALIGN_MEAN%22,%22crossSeriesReducer%22:%22REDUCE_SUM%22,%22groupByFields%22:%5B%22resource.label.%5C%22project_id%5C%22%22%5D%7D,%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22%7D%5D%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLines%22:%5B%5D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D,%22isAutoRefresh%22:true,%22timeSelection%22:%7B%22timeRange%22:%221w%22%7D%7D",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aliasBy": "{{resource.label.project_id}}",
     "alignOptions": [
      {
       "expanded": true,
       "label": "Alignment options",
       "options": [
        {
         "label": "interpolate",
         "metricKinds": [ "GAUGE" ],
         "text": "interpolate",
         "value": "ALIGN_INTERPOLATE",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "next older",
         "metricKinds": [ "GAUGE" ],
         "text": "next older",
         "value": "ALIGN_NEXT_OLDER",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "DISTRIBUTION",
          "STRING",
          "VALUE_TYPE_UNSPECIFIED",
          "BOOL"
         ]
        },
        {
         "label": "min",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "min",
         "value": "ALIGN_MIN",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "max",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "max",
         "value": "ALIGN_MAX",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "mean",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "mean",
         "value": "ALIGN_MEAN",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "count",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "count",
         "value": "ALIGN_COUNT",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "BOOL"
         ]
        },
        {
         "label": "sum",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "sum",
         "value": "ALIGN_SUM",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY",
          "DISTRIBUTION"
         ]
        },
        {
         "label": "stddev",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "stddev",
         "value": "ALIGN_STDDEV",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        },
        {
         "label": "percent change",
         "metricKinds": [
          "GAUGE",
          "DELTA"
         ],
         "text": "percent change",
         "value": "ALIGN_PERCENT_CHANGE",
         "valueTypes": [
          "INT64",
          "DOUBLE",
          "MONEY"
         ]
        }
       ]
      }
     ],
     "alignmentPeriod": "stackdriver-auto",
     "crossSeriesReducer": "REDUCE_COUNT",
     "defaultProject": "loading project...",
     "groupBys": [ "resource.label.project_id" ],
     "lastQuery": "aggregation.alignmentPeriod=+3600s&aggregation.crossSeriesReducer=REDUCE_STDDEV&aggregation.groupByFields=resource.label.project_id&aggregation.perSeriesAligner=ALIGN_INTERPOLATE&filter=metric.type=\"compute.googleapis.com/instance/cpu/utilization\"&interval.endTime=2020-04-01T17:29:54Z&interval.startTime=2020-03-25T17:29:54Z&view=FULL",
     "metricKind": "GAUGE",
     "metricType": "compute.googleapis.com/instance/cpu/utilization",
     "perSeriesAligner": "ALIGN_INTERPOLATE",
     "projectName": "fxci-production-logging",
     "unit": "10^2.%",
     "usedAlignmentPeriod": 3600,
     "valueType": "DOUBLE"
    }
   ]
  }
 ]
}