apiVersion: folder.grafana.app/v1beta1
kind: Folder
metadata:
  annotations:
    grafana.app/folder: edtgaia1z6waoe
  labels: {}
  name: cedp4g145xuyod
  namespace: default
spec:
  description: ""
  title: RelSRE Development
