apiVersion: folder.grafana.app/v1beta1
kind: Folder
metadata:
  annotations:
    grafana.app/folder: cffmfl1sfr1moe
  labels: {}
  name: cfm3q22tcfpq8a
  namespace: default
spec:
  description: ""
  title: Mac
