apiVersion: folder.grafana.app/v1beta1
kind: Folder
metadata:
  annotations:
    grafana.app/folder: efmrv608qkr28f
  labels: {}
  name: ffmrv6e11wge8e
  namespace: default
spec:
  description: ""
  title: GCP
